// ~120 eventos curados para v1 (PLAN §F5/paso-4).
// Distribución por categoría (canónicas PLAN §3.4):
//   militar      | politico | religioso | cientifico | cultural | economico | desastre
// Coverage temporal -3000 BCE → 1900 CE; eventos modernos post-1900 dejados para v2.
//
// polities[] lista los polities en nuestro v1 (50) que estuvieron involucrados.
// Si todos los participantes están fuera de v1, polities queda [] (válido).

export const EVENTS_SEED = [
  // ─── BCE — antigüedad temprana ──────────────────────────────────────────
  { id: 'codigo-hammurabi', name: 'Promulgación del Código de Hammurabi', year: -1754,
    polities: ['babilonia'], region: 'medio-oriente', category: 'politico', tags: ['codigo-legal', 'mesopotamia'],
    sources: ['https://es.wikipedia.org/wiki/Código_de_Hammurabi'],
    body: 'Hammurabi de Babilonia promulgó uno de los primeros corpus legales documentados — 282 leyes inscritas en una estela de basalto.' },
  { id: 'codificacion-vedas', name: 'Codificación de los Vedas', year: -1200,
    polities: [], region: 'sur-asia', category: 'religioso', tags: ['hinduismo', 'texto-sagrado'],
    sources: ['https://es.wikipedia.org/wiki/Vedas'],
    body: 'Compilación final de los himnos védicos en el norte de la India. Cimiento literario del hinduismo.' },
  { id: 'fundacion-cartago', name: 'Fundación de Cartago', year: -814,
    polities: ['cartago'], region: 'mediterraneo', category: 'politico', tags: ['fenicia', 'colonia'],
    sources: ['https://es.wikipedia.org/wiki/Cartago'],
    body: 'Colonos fenicios de Tiro liderados (según la leyenda) por la reina Dido fundan Cartago — futuro centro púnico mediterráneo.' },
  { id: 'codificacion-avesta', name: 'Compilación inicial del Avesta', year: -600,
    polities: [], region: 'medio-oriente', category: 'religioso', tags: ['zoroastrismo', 'texto-sagrado'],
    sources: ['https://es.wikipedia.org/wiki/Avesta'],
    body: 'Codificación oral inicial de los textos zoroastrianos atribuidos a Zaratustra. Escritura definitiva siglos después bajo los sasánidas.' },
  { id: 'iluminacion-buda', name: 'Iluminación de Siddhartha Gautama', year: -528,
    polities: [], region: 'sur-asia', category: 'religioso', tags: ['budismo', 'bodhi'],
    sources: ['https://es.wikipedia.org/wiki/Iluminación_(budismo)'],
    body: 'Siddhartha Gautama alcanza la iluminación bajo el árbol Bodhi en Bodh Gaya. Inicio del budismo como tradición predicativa.' },
  { id: 'batalla-maraton', name: 'Batalla de Maratón', year: -490,
    polities: ['imperio-persa-aquemenida'], region: 'mediterraneo', category: 'militar', tags: ['guerra-medica'],
    sources: ['https://es.wikipedia.org/wiki/Batalla_de_Maratón'],
    body: 'Victoria ateniense contra la fuerza expedicionaria de Darío I, deteniendo el primer intento de invasión persa de Grecia continental.' },
  { id: 'batalla-termopilas', name: 'Batalla de las Termópilas', year: -480,
    polities: ['imperio-persa-aquemenida'], region: 'mediterraneo', category: 'militar', tags: ['guerra-medica', 'leonidas'],
    sources: ['https://es.wikipedia.org/wiki/Batalla_de_las_Termópilas'],
    body: 'Resistencia espartana de Leónidas contra el ejército masivo de Jerjes I. Derrota táctica pero victoria moral; precede Salamina.' },
  { id: 'batalla-salamina', name: 'Batalla de Salamina', year: -480,
    polities: ['imperio-persa-aquemenida'], region: 'mediterraneo', category: 'militar', tags: ['guerra-medica', 'naval'],
    sources: ['https://es.wikipedia.org/wiki/Batalla_de_Salamina'],
    body: 'Victoria naval griega contra la flota persa, punto de inflexión de la Segunda Guerra Médica. Jerjes I se retira.' },
  { id: 'batalla-gaugamela', name: 'Batalla de Gaugamela', year: -331,
    polities: ['imperio-persa-aquemenida', 'macedonia-helenistica'], region: 'medio-oriente', category: 'militar', tags: ['conquista', 'darius-iii'],
    sources: ['https://es.wikipedia.org/wiki/Batalla_de_Gaugamela'],
    body: 'Victoria decisiva de Alejandro Magno sobre Darío III, sellando la conquista del Imperio Aqueménida.' },
  { id: 'muerte-alejandro-magno', name: 'Muerte de Alejandro Magno', year: -323,
    polities: ['macedonia-helenistica'], region: 'medio-oriente', category: 'politico', tags: ['helenismo', 'diadocos'],
    sources: ['https://es.wikipedia.org/wiki/Alejandro_Magno'],
    body: 'Alejandro muere en Babilonia a los 32 años. Sus generales (diadocos) se reparten el imperio, iniciando el periodo helenístico.' },
  { id: 'batalla-kalinga', name: 'Batalla de Kalinga', year: -261,
    polities: ['imperio-maurya'], region: 'sur-asia', category: 'militar', tags: ['ashoka', 'conversion-budista'],
    sources: ['https://es.wikipedia.org/wiki/Guerra_de_Kalinga'],
    body: 'Sangrienta conquista de Kalinga por Ashoka. La masacre provoca su conversión al budismo y un giro de 180° hacia la promoción del dhamma.' },
  { id: 'gran-muralla-qin', name: 'Construcción inicial de la Gran Muralla', year: -221,
    polities: [], region: 'este-asia', category: 'politico', tags: ['qin', 'fortificacion'],
    sources: ['https://es.wikipedia.org/wiki/Gran_Muralla_China'],
    body: 'Qin Shi Huang ordena conectar fortificaciones preexistentes en la frontera norte. Versión Ming (1368-1644) es la que sobrevive hoy.' },
  { id: 'septuaginta', name: 'Traducción de la Septuaginta', year: -250,
    polities: ['macedonia-helenistica'], region: 'norte-africa', category: 'religioso', tags: ['judaismo', 'helenismo', 'alejandria'],
    sources: ['https://es.wikipedia.org/wiki/Septuaginta'],
    body: 'Traducción al griego de la Torá hebrea, encargada por Ptolomeo II en Alejandría. Conecta judaísmo con mundo helénico; influye cristianismo posterior.' },
  { id: 'batalla-cannas', name: 'Batalla de Cannas', year: -216,
    polities: ['cartago', 'roma'], region: 'mediterraneo', category: 'militar', tags: ['segunda-guerra-punica', 'anibal'],
    sources: ['https://es.wikipedia.org/wiki/Batalla_de_Cannas'],
    body: 'Aníbal aniquila al ejército romano más grande jamás reunido contra él. Roma sobrevive pero pierde decenas de miles. Modelo de doble envolvimiento.' },
  { id: 'destruccion-cartago', name: 'Destrucción de Cartago', year: -146,
    polities: ['cartago', 'roma'], region: 'mediterraneo', category: 'militar', tags: ['tercera-guerra-punica'],
    sources: ['https://es.wikipedia.org/wiki/Tercera_Guerra_Púnica'],
    body: 'Roma destruye Cartago al final de la Tercera Guerra Púnica. Ciudad arrasada, suelo simbólicamente "salado", supervivientes esclavizados.' },
  { id: 'apertura-ruta-seda', name: 'Apertura formal de la Ruta de la Seda', year: -130,
    polities: ['dinastia-han'], region: 'este-asia', category: 'economico', tags: ['comercio-euroasiatico', 'zhang-qian'],
    sources: ['https://es.wikipedia.org/wiki/Ruta_de_la_Seda'],
    body: 'Tras las misiones de Zhang Qian a Asia Central, el emperador Han Wu Di formaliza el comercio terrestre que conectaría China con el Mediterráneo.' },
  { id: 'codificacion-bhagavad-gita', name: 'Codificación de la Bhagavad Gita', year: -200,
    polities: [], region: 'sur-asia', category: 'religioso', tags: ['hinduismo', 'mahabharata'],
    sources: ['https://es.wikipedia.org/wiki/Bhagavad_guita'],
    body: 'Compilación del diálogo entre Krishna y Arjuna inserto en el Mahabharata. Texto fundamental del hinduismo devocional y filosófico.' },
  { id: 'asesinato-julio-cesar', name: 'Asesinato de Julio César', year: -44,
    polities: ['roma'], region: 'mediterraneo', category: 'politico', tags: ['idus-de-marzo', 'fin-republica'],
    sources: ['https://es.wikipedia.org/wiki/Asesinato_de_Julio_César'],
    body: 'César asesinado por conspiradores senatoriales liderados por Bruto y Casio en los Idus de Marzo. Desencadena la segunda guerra civil romana y, eventualmente, el Principado.' },
  { id: 'batalla-actium', name: 'Batalla de Actium', year: -31,
    polities: ['roma', 'egipto-faraonico', 'macedonia-helenistica'], region: 'mediterraneo', category: 'militar', tags: ['octavio', 'marco-antonio', 'cleopatra'],
    sources: ['https://es.wikipedia.org/wiki/Batalla_de_Accio'],
    body: 'Victoria de Octavio sobre Marco Antonio y Cleopatra. Suicidios subsecuentes. Egipto pasa a ser provincia romana, fin del periodo helenístico.' },
  { id: 'publicacion-eneida', name: 'Publicación póstuma de la Eneida', year: -19,
    polities: ['roma'], region: 'mediterraneo', category: 'cultural', tags: ['virgilio', 'epica'],
    sources: ['https://es.wikipedia.org/wiki/Eneida'],
    body: 'Virgilio muere antes de revisar su Eneida; Augusto ordena publicarla. Épica fundacional de Roma que la vincula a Eneas troyano.' },

  // ─── CE — primer milenio ────────────────────────────────────────────────
  { id: 'crucifixion-jesus', name: 'Crucifixión de Jesús de Nazaret', year: 30,
    polities: ['roma'], region: 'medio-oriente', category: 'religioso', tags: ['cristianismo', 'foundational'],
    sources: ['https://es.wikipedia.org/wiki/Crucifixión_de_Jesús'],
    body: 'Ejecución de Jesús bajo Poncio Pilato, prefecto romano de Judea. Hecho fundacional del cristianismo según la tradición.' },
  { id: 'destruccion-segundo-templo', name: 'Destrucción del Segundo Templo de Jerusalén', year: 70,
    polities: ['roma'], region: 'medio-oriente', category: 'religioso', tags: ['judaismo', 'judaeo-romana'],
    sources: ['https://es.wikipedia.org/wiki/Destrucción_del_Segundo_Templo_de_Jerusalén'],
    body: 'Tito destruye el Templo durante la Guerra Judeo-Romana. Inicio del judaísmo rabínico (post-templário) y dispersión de la diáspora.' },
  { id: 'erupcion-vesubio', name: 'Erupción del Vesubio', year: 79,
    polities: ['roma'], region: 'mediterraneo', category: 'desastre', tags: ['volcan', 'pompeya'],
    sources: ['https://es.wikipedia.org/wiki/Erupción_del_Vesubio_(79)'],
    body: 'Erupción que sepulta Pompeya y Herculano. Plinio el Joven documenta el evento; Plinio el Viejo muere intentando rescatar refugiados.' },
  { id: 'invencion-papel-china', name: 'Invención del papel (perfeccionado)', year: 105,
    polities: ['dinastia-han'], region: 'este-asia', category: 'cientifico', tags: ['cai-lun', 'tecnologia'],
    sources: ['https://es.wikipedia.org/wiki/Historia_del_papel'],
    body: 'Cai Lun, eunuco de la corte Han del Este, perfecciona el proceso de fabricación de papel a partir de cortezas y harapos. Difusión hacia el oeste tomará 800 años.' },
  { id: 'edicto-milan', name: 'Edicto de Milán', year: 313,
    polities: ['roma'], region: 'mediterraneo', category: 'religioso', tags: ['cristianismo', 'tolerancia'],
    sources: ['https://es.wikipedia.org/wiki/Edicto_de_Milán'],
    body: 'Constantino I y Licinio decretan la tolerancia religiosa imperial, terminando las persecuciones sistemáticas al cristianismo.' },
  { id: 'concilio-nicea', name: 'Concilio de Nicea', year: 325,
    polities: ['roma'], region: 'mediterraneo', category: 'religioso', tags: ['cristianismo', 'credo-niceno'],
    sources: ['https://es.wikipedia.org/wiki/Primer_Concilio_de_Nicea'],
    body: 'Primer concilio ecuménico cristiano, convocado por Constantino. Define el Credo de Nicea contra el arrianismo; establece la fecha de la Pascua.' },
  { id: 'cristianizacion-aksum', name: 'Cristianización del Reino de Aksum', year: 340,
    polities: ['imperio-aksum'], region: 'africa-subsahariana', category: 'religioso', tags: ['cristianismo', 'ezana'],
    sources: ['https://es.wikipedia.org/wiki/Imperio_aksumita'],
    body: 'El rey Ezana adopta el cristianismo como religión estatal. Aksum se convierte en el segundo estado cristiano oficial tras Armenia.' },
  { id: 'edicto-tesalonica', name: 'Edicto de Tesalónica', year: 380,
    polities: ['roma'], region: 'mediterraneo', category: 'religioso', tags: ['cristianismo', 'teodosio'],
    sources: ['https://es.wikipedia.org/wiki/Edicto_de_Tesalónica'],
    body: 'Teodosio I declara el cristianismo niceno religión oficial del Imperio Romano. Persecución de paganismo y herejías arrianas.' },
  { id: 'saqueo-roma-410', name: 'Saqueo de Roma por los visigodos', year: 410,
    polities: ['roma'], region: 'mediterraneo', category: 'militar', tags: ['alarico', 'visigodos'],
    sources: ['https://es.wikipedia.org/wiki/Saqueo_de_Roma_(410)'],
    body: 'Alarico I saquea Roma — primer asalto a la Urbs en 800 años. Trauma cultural que motiva a Agustín de Hipona a escribir La Ciudad de Dios.' },
  { id: 'caida-imperio-romano-occidente', name: 'Caída del Imperio Romano de Occidente', year: 476,
    polities: ['roma'], region: 'mediterraneo', category: 'politico', tags: ['romulo-augustulo', 'odoacro'],
    sources: ['https://es.wikipedia.org/wiki/Caída_del_Imperio_romano_de_Occidente'],
    body: 'Odoacro, general germánico, depone al último emperador occidental Rómulo Augústulo. Fecha tradicional del fin de la Antigüedad clásica.' },
  { id: 'aryabhatiya', name: 'Publicación de Aryabhatiya', year: 499,
    polities: ['imperio-gupta'], region: 'sur-asia', category: 'cientifico', tags: ['matematicas', 'astronomia', 'cero'],
    sources: ['https://es.wikipedia.org/wiki/Aryabhatiya'],
    body: 'Aryabhata publica su tratado matemático-astronómico. Sistema decimal posicional, π con 4 decimales, propone rotación de la Tierra.' },
  { id: 'peste-justiniana', name: 'Peste de Justiniano', year: 541, year_end: 549,
    polities: ['imperio-bizantino', 'imperio-sasanida'], region: 'mediterraneo', category: 'desastre', tags: ['peste-bubonica', 'demografia'],
    sources: ['https://es.wikipedia.org/wiki/Plaga_de_Justiniano'],
    body: 'Primera pandemia documentada de peste bubónica, originada cerca de Etiopía. Mata estimados 30-50 millones; debilita el Imperio Bizantino justo cuando Justiniano intentaba recuperar Occidente.' },
  { id: 'hijra', name: 'Hégira de Mahoma', year: 622,
    polities: [], region: 'medio-oriente', category: 'religioso', tags: ['islam', 'medina'],
    sources: ['https://es.wikipedia.org/wiki/Hégira'],
    body: 'Mahoma emigra de Meca a Medina huyendo de la persecución. Fecha de inicio del calendario islámico; consolidación política inicial del islam.' },
  { id: 'batalla-yarmuk', name: 'Batalla de Yarmuk', year: 636,
    polities: ['imperio-bizantino'], region: 'medio-oriente', category: 'militar', tags: ['conquista-musulmana'],
    sources: ['https://es.wikipedia.org/wiki/Batalla_del_Yarmuk'],
    body: 'Decisiva victoria musulmana sobre los bizantinos en Siria. Inicio de la conquista árabe del Levante, Egipto y Norte de África.' },
  { id: 'caida-sasanida-nahavand', name: 'Batalla de Nahavand', year: 642,
    polities: ['imperio-sasanida'], region: 'medio-oriente', category: 'militar', tags: ['conquista-musulmana', 'fin-sasanida'],
    sources: ['https://es.wikipedia.org/wiki/Batalla_de_Nihawānd'],
    body: 'Conquista musulmana derrota a los sasánidas. Yazdegerd III, último sah, huye y muere asesinado en 651. Fin del Imperio Sasánida.' },
  { id: 'batalla-tours', name: 'Batalla de Tours / Poitiers', year: 732,
    polities: [], region: 'europa', category: 'militar', tags: ['carlos-martel', 'reconquista-temprana'],
    sources: ['https://es.wikipedia.org/wiki/Batalla_de_Poitiers_(732)'],
    body: 'Carlos Martel detiene el avance del Califato Omeya en Francia. Frenó la expansión musulmana hacia el norte de los Pirineos.' },
  { id: 'batalla-talas', name: 'Batalla de Talas', year: 751,
    polities: ['califato-abasi', 'dinastia-tang'], region: 'estepa', category: 'militar', tags: ['frontera-cultural'],
    sources: ['https://es.wikipedia.org/wiki/Batalla_de_Talas'],
    body: 'Choque entre el Califato Abasí y la China Tang. Tras la derrota china, los prisioneros transmiten al mundo islámico la técnica del papel — clave en la transmisión del conocimiento.' },
  { id: 'fundacion-bagdad', name: 'Fundación de Bagdad', year: 762,
    polities: ['califato-abasi'], region: 'medio-oriente', category: 'politico', tags: ['al-mansur', 'capital'],
    sources: ['https://es.wikipedia.org/wiki/Bagdad'],
    body: 'Al-Mansur funda Madinat al-Salam (Bagdad) como nueva capital abasí. Se convertirá en el centro intelectual y comercial del mundo islámico.' },
  { id: 'coronacion-carlomagno', name: 'Coronación de Carlomagno', year: 800,
    polities: [], region: 'europa', category: 'politico', tags: ['emperador', 'iglesia'],
    sources: ['https://es.wikipedia.org/wiki/Carlomagno'],
    body: 'El papa León III corona a Carlomagno como Emperador de los Romanos en Roma. Primera reivindicación cristiana de la dignidad imperial occidental post-476.' },
  { id: 'casa-sabiduria', name: 'Apogeo de la Casa de la Sabiduría', year: 830,
    polities: ['califato-abasi'], region: 'medio-oriente', category: 'cultural', tags: ['traducciones', 'al-mamun'],
    sources: ['https://es.wikipedia.org/wiki/Casa_de_la_Sabiduría'],
    body: 'Bajo el califa Al-Mamun, la Casa de la Sabiduría en Bagdad alcanza su apogeo. Traducción sistemática del corpus griego al árabe; matemáticas, óptica, medicina, filosofía.' },
  { id: 'tratado-verdun', name: 'Tratado de Verdún', year: 843,
    polities: [], region: 'europa', category: 'politico', tags: ['carolingio', 'particion'],
    sources: ['https://es.wikipedia.org/wiki/Tratado_de_Verdún'],
    body: 'Los tres nietos de Carlomagno dividen el Imperio Carolingio en Francia Occidental (futuro reino de Francia), Lotaringia y Francia Oriental (futura Alemania).' },
  { id: 'descubrimiento-polvora', name: 'Descubrimiento de la pólvora', year: 850,
    polities: ['dinastia-tang'], region: 'este-asia', category: 'cientifico', tags: ['alquimia', 'taoista'],
    sources: ['https://es.wikipedia.org/wiki/Pólvora'],
    body: 'Alquimistas daoístas chinos en busca del elixir de inmortalidad descubren la mezcla salitre + carbón + azufre. Aplicaciones militares masivas siglos después.' },

  // ─── CE — segundo milenio (1000-1500) ────────────────────────────────────
  { id: 'brujula-china', name: 'Brújula magnética náutica', year: 1080,
    polities: ['dinastia-song'], region: 'este-asia', category: 'cientifico', tags: ['navegacion', 'shen-kuo'],
    sources: ['https://es.wikipedia.org/wiki/Brújula'],
    body: 'Shen Kuo describe en sus Ensayos del Estanque de los Pinceles el uso de agujas magnetizadas para navegación. Transmisión a Europa vía mundo islámico.' },
  { id: 'imprenta-tipos-moviles-bi-sheng', name: 'Imprenta china de tipos móviles', year: 1040,
    polities: ['dinastia-song'], region: 'este-asia', category: 'cientifico', tags: ['imprenta', 'bi-sheng'],
    sources: ['https://es.wikipedia.org/wiki/Bi_Sheng'],
    body: 'Bi Sheng inventa los tipos móviles de cerámica. Tecnología no se difunde masivamente en China por el costo, pero llega a Corea y Europa siglos después.' },
  { id: 'cisma-oriente', name: 'Cisma de Oriente', year: 1054,
    polities: ['imperio-bizantino'], region: 'mediterraneo', category: 'religioso', tags: ['cristianismo', 'catolicismo-ortodoxia'],
    sources: ['https://es.wikipedia.org/wiki/Cisma_de_Oriente_y_Occidente'],
    body: 'Excomuniones recíprocas entre el papa León IX y el patriarca Miguel I Cerulario. Cristalización formal de la división católico-ortodoxa.' },
  { id: 'batalla-hastings', name: 'Batalla de Hastings', year: 1066,
    polities: ['reino-de-inglaterra'], region: 'europa', category: 'militar', tags: ['guillermo-conquistador', 'normando'],
    sources: ['https://es.wikipedia.org/wiki/Batalla_de_Hastings'],
    body: 'Guillermo de Normandía derrota a Harold II en Hastings. Inicio de la conquista normanda de Inglaterra — transforma idioma, derecho e instituciones.' },
  { id: 'batalla-manzikert', name: 'Batalla de Manzikert', year: 1071,
    polities: ['imperio-bizantino'], region: 'medio-oriente', category: 'militar', tags: ['turcos-selyúcidas', 'fin-anatolia-bizantina'],
    sources: ['https://es.wikipedia.org/wiki/Batalla_de_Manzikert'],
    body: 'Turcos selyúcidas derrotan a los bizantinos en Anatolia oriental. Inicio del desplazamiento bizantino y la turkización de Anatolia.' },
  { id: 'primera-cruzada', name: 'Primera Cruzada', year: 1096, year_end: 1099,
    polities: ['imperio-bizantino'], region: 'medio-oriente', category: 'militar', tags: ['cristianismo', 'jerusalen'],
    sources: ['https://es.wikipedia.org/wiki/Primera_Cruzada'],
    body: 'Convocada por Urbano II en Clermont (1095), captura Jerusalén en 1099 con masacre de habitantes musulmanes y judíos. Inicia 200 años de presencia franca en Levante.' },
  { id: 'optica-alhacen', name: 'Tratado de Óptica de Alhacén', year: 1021,
    polities: ['califato-fatimi'], region: 'norte-africa', category: 'cientifico', tags: ['optica', 'metodo-experimental'],
    sources: ['https://es.wikipedia.org/wiki/Kitab_al-Manazir'],
    body: 'Ibn al-Haytham publica Kitab al-Manazir en El Cairo. Refuta la teoría de la emisión visual y formula el método experimental — siglos antes de la Revolución Científica europea.' },
  { id: 'brihadeeswara', name: 'Construcción del Templo Brihadeeswara', year: 1010,
    polities: ['imperio-chola'], region: 'sur-asia', category: 'cultural', tags: ['hinduismo', 'arquitectura', 'tamil'],
    sources: ['https://es.wikipedia.org/wiki/Templo_Brihadisvara'],
    body: 'Rajaraja Chola I completa el templo monumental de Shiva en Thanjavur. Cúspide arquitectónica del periodo Chola; granito masivo, escala sin precedentes en Sur de India.' },
  { id: 'angkor-wat', name: 'Construcción de Angkor Wat', year: 1150,
    polities: ['imperio-khmer'], region: 'sudeste-asia', category: 'cultural', tags: ['hinduismo-vishnu', 'jemer'],
    sources: ['https://es.wikipedia.org/wiki/Angkor_Wat'],
    body: 'Suryavarman II completa el complejo de templos más grande del mundo dedicado a Vishnu. Posteriormente convertido a uso budista bajo Jayavarman VII.' },
  { id: 'magna-carta', name: 'Magna Carta', year: 1215,
    polities: ['reino-de-inglaterra'], region: 'europa', category: 'politico', tags: ['constitucionalismo', 'juan-sin-tierra'],
    sources: ['https://es.wikipedia.org/wiki/Carta_Magna'],
    body: 'Los barones ingleses fuerzan al rey Juan sin Tierra a aceptar la Magna Carta, limitando el poder real. Precedente del constitucionalismo y del habeas corpus.' },
  { id: 'unificacion-mongol', name: 'Unificación mongola por Genghis Khan', year: 1206,
    polities: ['imperio-mongol'], region: 'estepa', category: 'politico', tags: ['fundacion-mongol', 'temujin'],
    sources: ['https://es.wikipedia.org/wiki/Gengis_Kan'],
    body: 'Temüjin es proclamado Genghis Khan en un gran kurultai. Unificación de las tribus mongolas; inicio de las conquistas que crearán el mayor imperio terrestre contiguo.' },
  { id: 'saqueo-bagdad-mongol', name: 'Saqueo de Bagdad por los mongoles', year: 1258,
    polities: ['califato-abasi', 'imperio-mongol'], region: 'medio-oriente', category: 'militar', tags: ['hulagu', 'fin-abasi', 'casa-sabiduria'],
    sources: ['https://es.wikipedia.org/wiki/Saqueo_de_Bagdad'],
    body: 'Hulagu Khan saquea Bagdad, ejecutando al último califa abasí y destruyendo la Casa de la Sabiduría — pérdida cultural islámica catastrófica.' },
  { id: 'batalla-ayn-jalut', name: 'Batalla de Ayn Jalut', year: 1260,
    polities: ['imperio-mongol'], region: 'medio-oriente', category: 'militar', tags: ['mamelucos', 'frenado-mongol'],
    sources: ['https://es.wikipedia.org/wiki/Batalla_de_Ain_Jalut'],
    body: 'Los mamelucos egipcios derrotan al Ilkanato mongol. Primer freno significativo a la expansión mongola en Asia occidental.' },
  { id: 'fundacion-yuan', name: 'Fundación de la dinastía Yuan', year: 1271,
    polities: ['imperio-mongol'], region: 'este-asia', category: 'politico', tags: ['kublai-khan', 'china-mongol'],
    sources: ['https://es.wikipedia.org/wiki/Dinastía_Yuan'],
    body: 'Kublai Khan proclama la dinastía Yuan en China, capital en Khanbaliq (Beijing). Primera dinastía no-Han a gobernar toda China.' },
  { id: 'conquista-song-yuan', name: 'Conquista mongola de los Song del Sur', year: 1279,
    polities: ['dinastia-song', 'imperio-mongol'], region: 'este-asia', category: 'militar', tags: ['fin-song', 'yuan'],
    sources: ['https://es.wikipedia.org/wiki/Batalla_de_Yamen'],
    body: 'Batalla naval de Yamen: los Yuan completan la conquista de los Song del Sur. China entera bajo dominio mongol por primera vez.' },
  { id: 'mansa-musa-hajj', name: 'Peregrinación de Mansa Musa a La Meca', year: 1324,
    polities: ['imperio-mali'], region: 'africa-subsahariana', category: 'cultural', tags: ['oro', 'visibilizacion-internacional'],
    sources: ['https://es.wikipedia.org/wiki/Mansa_Musa'],
    body: 'Mansa Musa cruza el Sahara con un séquito enorme y reparte tanto oro en El Cairo que devalúa la moneda local por 10+ años. Coloca al Imperio Mali en mapas árabes y europeos.' },
  { id: 'fundacion-tenochtitlan', name: 'Fundación de Tenochtitlan', year: 1325,
    polities: ['imperio-azteca'], region: 'americas', category: 'politico', tags: ['mexicas', 'lago-texcoco'],
    sources: ['https://es.wikipedia.org/wiki/Fundación_de_Tenochtitlan'],
    body: 'Los mexicas fundan Tenochtitlan en una isla del lago Texcoco, donde según el mito vieron un águila devorando una serpiente sobre un nopal — escena del actual escudo mexicano.' },
  { id: 'peste-negra', name: 'Peste Negra en Europa', year: 1347, year_end: 1351,
    polities: ['imperio-bizantino'], region: 'europa', category: 'desastre', tags: ['peste-bubonica', 'demografia'],
    sources: ['https://es.wikipedia.org/wiki/Peste_negra'],
    body: 'Pandemia originada en Asia Central; llega a Europa vía rutas comerciales. Mata 30-60% de la población europea (~25-50M). Transforma economía, religión, demografía durante siglos.' },
  { id: 'batalla-kosovo', name: 'Batalla de Kosovo', year: 1389,
    polities: ['imperio-otomano'], region: 'europa', category: 'militar', tags: ['otomanos', 'serbia'],
    sources: ['https://es.wikipedia.org/wiki/Batalla_de_Kosovo'],
    body: 'Otomanos derrotan al príncipe Lazar de Serbia. Inicio de cinco siglos de dominio otomano sobre los Balcanes; trauma fundacional del nacionalismo serbio.' },
  { id: 'expediciones-zheng-he', name: 'Expediciones navales de Zheng He', year: 1405, year_end: 1433,
    polities: ['dinastia-ming'], region: 'este-asia', category: 'politico', tags: ['naval', 'tributo'],
    sources: ['https://es.wikipedia.org/wiki/Zheng_He'],
    body: 'Siete expediciones marítimas con flotas masivas (hasta 300 barcos, 28,000 hombres) hasta Arabia y África Oriental. Tras la muerte del Yongle, China abandona la política marítima.' },
  { id: 'caida-constantinopla-1453', name: 'Caída de Constantinopla', year: 1453,
    polities: ['imperio-bizantino', 'imperio-otomano'], region: 'medio-oriente', category: 'militar', tags: ['mehmed-ii', 'fin-bizancio'],
    sources: ['https://es.wikipedia.org/wiki/Caída_de_Constantinopla'],
    body: 'Mehmed II conquista Constantinopla con cañones de bronce masivos. Fin del Imperio Bizantino y fecha tradicional del fin de la Edad Media.' },
  { id: 'imprenta-gutenberg', name: 'Imprenta de tipos móviles en Europa', year: 1455,
    polities: [], region: 'europa', category: 'cientifico', tags: ['gutenberg', 'biblia'],
    sources: ['https://es.wikipedia.org/wiki/Imprenta'],
    body: 'Johannes Gutenberg imprime la Biblia de 42 líneas en Maguncia. Su técnica de tipos móviles metálicos transforma la difusión del conocimiento en Europa.' },
  { id: 'caida-granada', name: 'Caída del Reino de Granada', year: 1492,
    polities: ['imperio-espanol'], region: 'europa', category: 'militar', tags: ['reconquista', 'reyes-catolicos'],
    sources: ['https://es.wikipedia.org/wiki/Conquista_de_Granada'],
    body: 'Boabdil entrega Granada a los Reyes Católicos, completando la Reconquista de la península ibérica tras 781 años de presencia musulmana.' },
  { id: 'llegada-colon-america', name: 'Llegada de Colón a América', year: 1492,
    polities: ['imperio-espanol'], region: 'americas', category: 'economico', tags: ['descubrimiento', 'intercambio-colombino'],
    sources: ['https://es.wikipedia.org/wiki/Descubrimiento_de_América'],
    body: 'Cristóbal Colón desembarca en Guanahaní (Bahamas). Inicio del intercambio colombino — uno de los eventos más transformadores de la historia humana.' },
  { id: 'expulsion-judios-espana', name: 'Expulsión de los judíos de España', year: 1492,
    polities: ['imperio-espanol'], region: 'europa', category: 'politico', tags: ['sefardies', 'limpieza-religiosa'],
    sources: ['https://es.wikipedia.org/wiki/Edicto_de_Granada'],
    body: 'Los Reyes Católicos decretan la expulsión de unos 200,000 judíos de Castilla y Aragón. Diáspora sefardí hacia el Imperio Otomano, Norte de África, Portugal, Holanda.' },
  { id: 'tratado-tordesillas', name: 'Tratado de Tordesillas', year: 1494,
    polities: ['imperio-espanol'], region: 'europa', category: 'politico', tags: ['castilla', 'portugal', 'particion-mundial'],
    sources: ['https://es.wikipedia.org/wiki/Tratado_de_Tordesillas'],
    body: 'España y Portugal dividen el mundo no-cristiano en zonas de influencia mediante una línea papal-arbitrada en el Atlántico. Base legal del colonialismo ibérico.' },

  // ─── CE — temprana modernidad (1500-1800) ────────────────────────────────
  { id: 'tesis-wittenberg', name: 'Tesis de Wittenberg de Lutero', year: 1517,
    polities: ['sacro-imperio-romano-germanico'], region: 'europa', category: 'religioso', tags: ['protestantismo', 'reforma'],
    sources: ['https://es.wikipedia.org/wiki/Las_95_tesis'],
    body: 'Martín Lutero clava (según la tradición) sus 95 Tesis en la puerta de la iglesia del castillo de Wittenberg, criticando las indulgencias. Inicio de la Reforma Protestante.' },
  { id: 'conquista-tenochtitlan', name: 'Conquista de Tenochtitlan', year: 1521,
    polities: ['imperio-azteca', 'imperio-espanol'], region: 'americas', category: 'militar', tags: ['cortes', 'fin-mexica'],
    sources: ['https://es.wikipedia.org/wiki/Sitio_de_Tenochtitlan'],
    body: 'Hernán Cortés con aliados tlaxcaltecas conquista Tenochtitlan tras sitio de 75 días. Cuauhtémoc capturado. Fin del imperio mexica; inicio de la Nueva España.' },
  { id: 'batalla-panipat-1526', name: 'Primera batalla de Panipat', year: 1526,
    polities: ['imperio-mogol'], region: 'sur-asia', category: 'militar', tags: ['babur', 'fundacion-mogol'],
    sources: ['https://es.wikipedia.org/wiki/Primera_batalla_de_Panipat'],
    body: 'Babur derrota al sultán de Delhi Ibrahim Lodi usando artillería. Fundación del Imperio Mogol.' },
  { id: 'captura-atahualpa', name: 'Captura de Atahualpa', year: 1532,
    polities: ['imperio-inca', 'imperio-espanol'], region: 'americas', category: 'militar', tags: ['cajamarca', 'pizarro'],
    sources: ['https://es.wikipedia.org/wiki/Captura_de_Atahualpa'],
    body: 'Francisco Pizarro captura al sapa inca Atahualpa en Cajamarca con 168 españoles. Atahualpa paga el rescate más grande de la historia (oro y plata) y es ejecutado igualmente.' },
  { id: 'cisma-anglicano', name: 'Cisma anglicano', year: 1534,
    polities: ['reino-de-inglaterra'], region: 'europa', category: 'religioso', tags: ['enrique-viii', 'anglicanismo'],
    sources: ['https://es.wikipedia.org/wiki/Acta_de_Supremacía'],
    body: 'Enrique VIII se autoproclama cabeza de la Iglesia de Inglaterra mediante el Acta de Supremacía. Ruptura con Roma motivada inicialmente por el divorcio de Catalina de Aragón.' },
  { id: 'fundacion-jesuitas', name: 'Fundación de la Compañía de Jesús', year: 1540,
    polities: ['imperio-espanol'], region: 'europa', category: 'religioso', tags: ['jesuitas', 'contrareforma', 'ignacio-loyola'],
    sources: ['https://es.wikipedia.org/wiki/Compañía_de_Jesús'],
    body: 'El papa Pablo III aprueba la orden religiosa fundada por Ignacio de Loyola. Punta de lanza de la Contrarreforma y de las misiones globales (Matteo Ricci en China, Xavier en Japón).' },
  { id: 'concilio-trento', name: 'Concilio de Trento', year: 1545, year_end: 1563,
    polities: [], region: 'europa', category: 'religioso', tags: ['catolicismo', 'contrareforma'],
    sources: ['https://es.wikipedia.org/wiki/Concilio_de_Trento'],
    body: 'Concilio ecuménico que responde a la Reforma Protestante: reafirma doctrina católica, reforma clero, condena protestantismo. Define el catolicismo moderno hasta el Vaticano II.' },
  { id: 'descubrimiento-potosi', name: 'Descubrimiento de la plata de Potosí', year: 1545,
    polities: ['imperio-espanol'], region: 'americas', category: 'economico', tags: ['plata', 'mita', 'globalizacion-monetaria'],
    sources: ['https://es.wikipedia.org/wiki/Potosí'],
    body: 'El Cerro Rico de Potosí (actual Bolivia) revela ser la mayor mina de plata del mundo. Trabajo forzado (mita) de indígenas; inicio de la globalización monetaria de la plata vía Manila.' },
  { id: 'paz-augsburgo', name: 'Paz de Augsburgo', year: 1555,
    polities: ['sacro-imperio-romano-germanico'], region: 'europa', category: 'politico', tags: ['cuius-regio-eius-religio', 'protestantismo'],
    sources: ['https://es.wikipedia.org/wiki/Paz_de_Augsburgo'],
    body: 'Carlos V acepta el principio cuius regio, eius religio: el príncipe determina la religión de su territorio. Catolicismo y luteranismo legalmente reconocidos en el SIRG.' },
  { id: 'batalla-lepanto', name: 'Batalla de Lepanto', year: 1571,
    polities: ['imperio-otomano', 'imperio-espanol'], region: 'mediterraneo', category: 'militar', tags: ['liga-santa', 'naval'],
    sources: ['https://es.wikipedia.org/wiki/Batalla_de_Lepanto'],
    body: 'La Liga Santa (España, Venecia, Estados Pontificios) derrota a la flota otomana en el Golfo de Patras. Primera derrota naval mayor otomana en el Mediterráneo; Cervantes pierde el uso de su mano izquierda allí.' },
  { id: 'derrota-armada-invencible', name: 'Derrota de la Armada Invencible', year: 1588,
    polities: ['imperio-espanol', 'reino-de-inglaterra'], region: 'europa', category: 'militar', tags: ['naval', 'protestantismo'],
    sources: ['https://es.wikipedia.org/wiki/Armada_Invencible'],
    body: 'La flota inglesa y mal tiempo destruyen la Armada española enviada por Felipe II. Marca el inicio del declive naval español y el ascenso de Inglaterra como potencia atlántica.' },
  { id: 'batalla-sekigahara', name: 'Batalla de Sekigahara', year: 1600,
    polities: ['shogunato-tokugawa'], region: 'este-asia', category: 'militar', tags: ['tokugawa-ieyasu', 'unificacion-japon'],
    sources: ['https://es.wikipedia.org/wiki/Batalla_de_Sekigahara'],
    body: 'Tokugawa Ieyasu derrota a la coalición de daimyos leales a Toyotomi. Le permite establecer el shogunato Tokugawa (1603), inaugurando 250 años de aislamiento y paz interna.' },
  { id: 'publicacion-don-quijote', name: 'Publicación del Don Quijote', year: 1605,
    polities: ['imperio-espanol'], region: 'europa', category: 'cultural', tags: ['cervantes', 'novela-moderna'],
    sources: ['https://es.wikipedia.org/wiki/Don_Quijote_de_la_Mancha'],
    body: 'Miguel de Cervantes publica la primera parte del Don Quijote. Considerada la primera novela moderna y una de las obras pivotales de la literatura mundial.' },
  { id: 'galileo-telescopio', name: 'Galileo perfecciona el telescopio astronómico', year: 1609,
    polities: [], region: 'europa', category: 'cientifico', tags: ['heliocentrismo', 'astronomia'],
    sources: ['https://es.wikipedia.org/wiki/Galileo_Galilei'],
    body: 'Galileo perfecciona el telescopio y lo apunta al cielo. Sus descubrimientos (lunas de Júpiter, fases de Venus, manchas solares) corroboran el modelo heliocéntrico copernicano.' },
  { id: 'mayflower-compact', name: 'Mayflower Compact', year: 1620,
    polities: ['reino-de-inglaterra'], region: 'americas', category: 'politico', tags: ['puritanos', 'autogobierno', 'colonia'],
    sources: ['https://es.wikipedia.org/wiki/Pacto_del_Mayflower'],
    body: 'Los puritanos del Mayflower firman un acuerdo de autogobierno antes de desembarcar en Cape Cod. Precedente del constitucionalismo americano y del federalismo colonial.' },
  { id: 'taj-mahal', name: 'Construcción del Taj Mahal', year: 1632, year_end: 1653,
    polities: ['imperio-mogol'], region: 'sur-asia', category: 'cultural', tags: ['shah-jahan', 'mausoleo', 'arquitectura'],
    sources: ['https://es.wikipedia.org/wiki/Taj_Mahal'],
    body: 'Shah Jahan ordena construir el mausoleo en mármol blanco para su esposa Mumtaz Mahal en Agra. Cumbre de la arquitectura mogol; Patrimonio de la Humanidad.' },
  { id: 'inicio-sakoku', name: 'Inicio del sakoku japonés', year: 1639,
    polities: ['shogunato-tokugawa'], region: 'este-asia', category: 'politico', tags: ['aislamiento', 'tokugawa-iemitsu'],
    sources: ['https://es.wikipedia.org/wiki/Sakoku'],
    body: 'El shogunato Tokugawa prohíbe casi todo contacto exterior. Sólo barcos chinos y holandeses pueden comerciar en Nagasaki bajo control estricto. Aislamiento dura 215 años.' },
  { id: 'caida-ming', name: 'Caída de la dinastía Ming', year: 1644,
    polities: ['dinastia-ming', 'dinastia-qing'], region: 'este-asia', category: 'politico', tags: ['manchu', 'qing'],
    sources: ['https://es.wikipedia.org/wiki/Dinastía_Qing'],
    body: 'Tras décadas de revueltas campesinas, el último emperador Ming Chongzhen se suicida cuando Pekín cae ante Li Zicheng. Los manchúes aprovechan el caos y fundan la dinastía Qing.' },
  { id: 'paz-westfalia', name: 'Paz de Westfalia', year: 1648,
    polities: ['sacro-imperio-romano-germanico'], region: 'europa', category: 'politico', tags: ['guerra-treinta-anos', 'soberania-estatal'],
    sources: ['https://es.wikipedia.org/wiki/Paz_de_Westfalia'],
    body: 'Termina la Guerra de los Treinta Años. Establece el principio de soberanía territorial — fundamento del sistema internacional moderno de estados-nación.' },
  { id: 'meditaciones-descartes', name: 'Meditaciones de Descartes', year: 1641,
    polities: [], region: 'europa', category: 'cultural', tags: ['filosofia', 'modernidad', 'cogito'],
    sources: ['https://es.wikipedia.org/wiki/Meditaciones_metafísicas'],
    body: 'René Descartes publica las Meditaciones metafísicas. El "cogito ergo sum" inaugura el racionalismo moderno y la filosofía del sujeto.' },
  { id: 'principia-newton', name: 'Publicación de los Principia de Newton', year: 1687,
    polities: ['reino-de-inglaterra'], region: 'europa', category: 'cientifico', tags: ['fisica', 'gravitacion', 'metodo-cientifico'],
    sources: ['https://es.wikipedia.org/wiki/Philosophiae_naturalis_principia_mathematica'],
    body: 'Isaac Newton publica Philosophiae Naturalis Principia Mathematica. Formula las tres leyes del movimiento y la ley de gravitación universal. Base de la mecánica clásica.' },
  { id: 'fundacion-san-petersburgo', name: 'Fundación de San Petersburgo', year: 1703,
    polities: ['imperio-ruso'], region: 'europa', category: 'politico', tags: ['pedro-el-grande', 'occidentalizacion'],
    sources: ['https://es.wikipedia.org/wiki/Historia_de_San_Petersburgo'],
    body: 'Pedro el Grande funda una nueva capital sobre pantanos en el Báltico, simbolizando la occidentalización forzada de Rusia. Capital imperial hasta 1918.' },
  { id: 'acta-union-britanica', name: 'Acta de Unión Inglaterra-Escocia', year: 1707,
    polities: ['reino-de-inglaterra'], region: 'europa', category: 'politico', tags: ['reino-unido', 'union'],
    sources: ['https://es.wikipedia.org/wiki/Acta_de_Unión_de_1707'],
    body: 'Las parlamentos de Inglaterra y Escocia se unen formando el Reino Unido de Gran Bretaña. Reforma constitucional pivotal del estado británico moderno.' },
  { id: 'batalla-plassey', name: 'Batalla de Plassey', year: 1757,
    polities: ['imperio-mogol', 'reino-de-inglaterra'], region: 'sur-asia', category: 'militar', tags: ['east-india-company', 'colonialismo'],
    sources: ['https://es.wikipedia.org/wiki/Batalla_de_Plassey'],
    body: 'La Compañía Inglesa de las Indias Orientales liderada por Robert Clive vence al nawab de Bengala. Inicio formal del dominio británico sobre India.' },
  { id: 'independencia-eeuu', name: 'Declaración de Independencia de EE.UU.', year: 1776,
    polities: ['reino-de-inglaterra'], region: 'americas', category: 'politico', tags: ['revolucion', 'jefferson'],
    sources: ['https://es.wikipedia.org/wiki/Declaración_de_Independencia_de_los_Estados_Unidos'],
    body: 'Las trece colonias se declaran independientes. Primer estado moderno fundado en principios ilustrados (igualdad, derechos naturales) — modelo para revoluciones posteriores.' },
  { id: 'revolucion-francesa', name: 'Revolución Francesa', year: 1789,
    polities: ['reino-de-francia'], region: 'europa', category: 'politico', tags: ['revolucion', 'derechos-humanos'],
    sources: ['https://es.wikipedia.org/wiki/Revolución_francesa'],
    body: 'Toma de la Bastilla (14 julio 1789), Declaración de los Derechos del Hombre y del Ciudadano. Fin del Antiguo Régimen francés y emergencia del concepto moderno de ciudadanía.' },

  // ─── CE — Siglo XIX (selección) ─────────────────────────────────────────
  { id: 'apertura-japon-perry', name: 'Apertura forzada de Japón', year: 1853,
    polities: ['shogunato-tokugawa'], region: 'este-asia', category: 'politico', tags: ['perry', 'sakoku', 'fin'],
    sources: ['https://es.wikipedia.org/wiki/Convención_de_Kanagawa'],
    body: 'El comodoro Matthew Perry de la US Navy fuerza a Japón a abrir puertos. Detona la Restauración Meiji (1868) y el fin del shogunato Tokugawa.' },
  { id: 'rebelion-taiping', name: 'Rebelión Taiping', year: 1850, year_end: 1864,
    polities: ['dinastia-qing'], region: 'este-asia', category: 'militar', tags: ['guerra-civil', 'cristianismo-sincretico'],
    sources: ['https://es.wikipedia.org/wiki/Rebelión_Taiping'],
    body: 'Guerra civil más letal del siglo XIX (~20-30M muertos). Hong Xiuquan, autoproclamado hermano menor de Jesús, lidera el "Reino Celestial de Gran Paz". Aplastada finalmente por los Qing con ayuda occidental.' },
  { id: 'rebelion-india-1857', name: 'Rebelión india de 1857', year: 1857,
    polities: ['imperio-mogol', 'reino-de-inglaterra'], region: 'sur-asia', category: 'militar', tags: ['cipayos', 'fin-mogol', 'raj'],
    sources: ['https://es.wikipedia.org/wiki/Rebelión_de_la_India_de_1857'],
    body: 'Sepoys del ejército de la Compañía de Indias Orientales se rebelan. Tras la represión británica, depone al último emperador mogol (Bahadur Shah II) y la Corona toma control directo (Raj británico, 1858).' },
  { id: 'guerras-opio', name: 'Guerras del Opio', year: 1839, year_end: 1860,
    polities: ['dinastia-qing', 'reino-de-inglaterra'], region: 'este-asia', category: 'militar', tags: ['imperialismo', 'tratados-desiguales'],
    sources: ['https://es.wikipedia.org/wiki/Guerras_del_Opio'],
    body: 'Dos guerras (1839-1842, 1856-1860) imponen el comercio de opio británico en China. Tratados desiguales: cesión de Hong Kong, indemnizaciones, apertura forzada de puertos. Inicio del "siglo de humillación" chino.' },
];
