// ~125 figuras curadas para v1 (PLAN §F4/paso-3 — max 5-10 por polity).
// Distribución: balance no-Eurocentric verificable con lint-balance --strict
// (cuota mínima ≥2 figuras por macro-región, en F4/paso-5 corremos check).
//
// IDs canónicos en Wikidata se incluyen sólo cuando la confianza es ≥95%.
// Resto: sebas/futuras sesiones pueden enriquecer cruzando con queries SPARQL.

export const FIGURES_SEED = [
  // ─── Mediterráneo (12) ──────────────────────────────────────────────────
  { id: 'amilcar-barca', name: 'Amílcar Barca', name_en: 'Hamilcar Barca', year_born: -275, year_died: -228,
    polity: ['cartago'], region: 'mediterraneo', role: 'militar', tags: ['general', 'barcida'],
    sources: ['https://es.wikipedia.org/wiki/Amílcar_Barca'],
    body: 'General cartaginés padre de Aníbal. Comandó las fuerzas púnicas al final de la Primera Guerra Púnica y fundó el dominio cartaginés en Hispania.' },
  { id: 'hannibal-barca', name: 'Aníbal Barca', name_en: 'Hannibal', year_born: -247, year_died: -183,
    polity: ['cartago'], region: 'mediterraneo', role: 'militar', tags: ['general', 'segunda-guerra-punica'],
    sources: ['https://es.wikipedia.org/wiki/Aníbal_Barca'],
    body: 'Estratega cartaginés que cruzó los Alpes con elefantes para invadir Italia en la Segunda Guerra Púnica. Derrotó a los romanos en Cannas (216 BCE) pero no pudo capturar Roma; murió en exilio por veneno.' },
  { id: 'filipo-ii-de-macedonia', name: 'Filipo II de Macedonia', name_en: 'Philip II of Macedon', year_born: -382, year_died: -336,
    polity: ['macedonia-helenistica'], region: 'mediterraneo', role: 'politico', tags: ['rey', 'reformador-militar'],
    sources: ['https://es.wikipedia.org/wiki/Filipo_II_de_Macedonia'],
    body: 'Rey de Macedonia (359-336 BCE), unificó Grecia bajo la Liga de Corinto y reformó la falange macedonia con la sarisa. Su asesinato dejó las conquistas pan-helénicas a su hijo Alejandro.' },
  { id: 'alejandro-magno', name: 'Alejandro Magno', name_en: 'Alexander the Great', year_born: -356, year_died: -323,
    polity: ['macedonia-helenistica'], region: 'mediterraneo', role: 'militar', tags: ['conquistador', 'helenismo'],
    wikidata: 'Q8409',
    sources: ['https://es.wikipedia.org/wiki/Alejandro_Magno'],
    body: 'Rey de Macedonia que en 13 años conquistó el Imperio Aqueménida desde Grecia hasta el Indo, fundando ~20 ciudades llamadas Alejandría. Su muerte temprana en Babilonia inicia el periodo helenístico.' },
  { id: 'ptolomeo-i-soter', name: 'Ptolomeo I Sóter', name_en: 'Ptolemy I Soter', year_born: -367, year_died: -283,
    polity: ['macedonia-helenistica'], region: 'mediterraneo', role: 'politico', tags: ['diadoco', 'egipto-ptolemaico'],
    sources: ['https://es.wikipedia.org/wiki/Ptolomeo_I'],
    body: 'General de Alejandro que tras la guerra de los diádocos se hizo con Egipto, fundando la dinastía Ptolemaica (305 BCE). Promotor de la Biblioteca de Alejandría.' },
  { id: 'julio-cesar', name: 'Julio César', name_en: 'Julius Caesar', year_born: -100, year_died: -44,
    polity: ['roma'], region: 'mediterraneo', role: 'politico', tags: ['general', 'dictador'],
    wikidata: 'Q1048',
    sources: ['https://es.wikipedia.org/wiki/Julio_César'],
    body: 'General romano que conquistó las Galias y cruzó el Rubicón (49 BCE) desatando la guerra civil que terminó con la República. Dictador perpetuo; asesinado en los Idus de Marzo del 44 BCE.' },
  { id: 'augusto', name: 'Augusto', name_en: 'Augustus', year_born: -63, year_died: 14,
    polity: ['roma'], region: 'mediterraneo', role: 'politico', tags: ['princeps', 'pax-romana'],
    wikidata: 'Q1405',
    sources: ['https://es.wikipedia.org/wiki/Augusto'],
    body: 'Primer emperador romano (27 BCE - 14 CE), sobrino-nieto y heredero de César. Estableció el Principado y la Pax Romana, reorganizando el imperio tras un siglo de guerras civiles.' },
  { id: 'ciceron', name: 'Cicerón', name_en: 'Cicero', year_born: -106, year_died: -43,
    polity: ['roma'], region: 'mediterraneo', role: 'filosofo', tags: ['orador', 'republicano'],
    wikidata: 'Q1541',
    sources: ['https://es.wikipedia.org/wiki/Cicerón'],
    body: 'Orador, filósofo y político romano de la República tardía. Su prosa estableció el latín culto; transmitió a Roma el estoicismo y la filosofía griega. Ejecutado tras oponerse a Marco Antonio.' },
  { id: 'virgilio', name: 'Virgilio', name_en: 'Virgil', year_born: -70, year_died: -19,
    polity: ['roma'], region: 'mediterraneo', role: 'artista', tags: ['poeta', 'eneida'],
    sources: ['https://es.wikipedia.org/wiki/Virgilio'],
    body: 'Poeta romano del círculo de Augusto, autor de las Bucólicas, las Geórgicas y la Eneida — épica fundacional de Roma que vincula la ciudad con el héroe troyano Eneas.' },
  { id: 'marco-aurelio', name: 'Marco Aurelio', name_en: 'Marcus Aurelius', year_born: 121, year_died: 180,
    polity: ['roma'], region: 'mediterraneo', role: 'filosofo', tags: ['emperador', 'estoicismo'],
    wikidata: 'Q1430',
    sources: ['https://es.wikipedia.org/wiki/Marco_Aurelio'],
    body: 'Emperador romano (161-180) y último de los "Cinco Buenos Emperadores". Sus Meditaciones, escritas durante campañas en el Danubio, son el manual estoico más leído de Occidente.' },
  { id: 'constantino-i', name: 'Constantino I', name_en: 'Constantine the Great', year_born: 272, year_died: 337,
    polity: ['roma'], region: 'mediterraneo', role: 'politico', tags: ['emperador', 'cristianizacion'],
    sources: ['https://es.wikipedia.org/wiki/Constantino_I'],
    body: 'Emperador romano (306-337) que con el Edicto de Milán (313) terminó las persecuciones a los cristianos y refundó Constantinopla como capital oriental (330). Iniciador del cristianismo institucional imperial.' },
  { id: 'justiniano-i', name: 'Justiniano I', name_en: 'Justinian I', year_born: 482, year_died: 565,
    polity: ['imperio-bizantino'], region: 'mediterraneo', role: 'politico', tags: ['emperador', 'codigo-justiniano'],
    sources: ['https://es.wikipedia.org/wiki/Justiniano_I'],
    body: 'Emperador bizantino (527-565), recuperó Italia, África y parte de Hispania. Promulgó el Corpus Iuris Civilis, base del derecho civil moderno. Ordenó construir Santa Sofía.' },

  // ─── Europa post-Roma (16) ──────────────────────────────────────────────
  { id: 'carlomagno', name: 'Carlomagno', name_en: 'Charlemagne', year_born: 747, year_died: 814,
    polity: [], region: 'europa', role: 'politico', tags: ['emperador', 'carolingio'],
    wikidata: 'Q3044',
    sources: ['https://es.wikipedia.org/wiki/Carlomagno'],
    body: 'Rey de los francos coronado emperador por el papa León III (800 CE) — primer intento de restauración occidental imperial post-Roma. Anticipa el Sacro Imperio Romano Germánico (no incluido como polity v1 por antecederlo en ~150 años).' },
  { id: 'oton-i-el-grande', name: 'Otón I el Grande', name_en: 'Otto the Great', year_born: 912, year_died: 973,
    polity: ['sacro-imperio-romano-germanico'], region: 'europa', role: 'politico', tags: ['emperador', 'fundador'],
    sources: ['https://es.wikipedia.org/wiki/Otón_I_del_Sacro_Imperio_Romano_Germánico'],
    body: 'Rey de Germania coronado emperador por el papa Juan XII en 962, fecha tradicionalmente considerada fundación del Sacro Imperio Romano Germánico.' },
  { id: 'federico-i-barbarossa', name: 'Federico I Barbarroja', name_en: 'Frederick I Barbarossa', year_born: 1122, year_died: 1190,
    polity: ['sacro-imperio-romano-germanico'], region: 'europa', role: 'politico', tags: ['emperador', 'cruzado'],
    sources: ['https://es.wikipedia.org/wiki/Federico_I_Barbarroja'],
    body: 'Emperador del Sacro Imperio (1155-1190). Disputó con la Liga Lombarda y el papado por el control de Italia. Murió ahogado durante la Tercera Cruzada.' },
  { id: 'carlos-v', name: 'Carlos V', name_en: 'Charles V', year_born: 1500, year_died: 1558,
    polity: ['sacro-imperio-romano-germanico', 'imperio-espanol'], region: 'europa', role: 'politico', tags: ['emperador', 'habsburgo'],
    wikidata: 'Q32500',
    sources: ['https://es.wikipedia.org/wiki/Carlos_I_de_España'],
    body: 'Emperador del Sacro Imperio Romano Germánico (1519-1556) y rey de España (1516-1556) — el primer dominio "en que no se ponía el sol". Lidió con la Reforma Protestante; abdicó dividiendo sus territorios entre Felipe II (España) y Fernando I (SIRG).' },
  { id: 'alfredo-el-grande', name: 'Alfredo el Grande', name_en: 'Alfred the Great', year_born: 849, year_died: 899,
    polity: ['reino-de-inglaterra'], region: 'europa', role: 'politico', tags: ['rey', 'wessex', 'reformador'],
    sources: ['https://es.wikipedia.org/wiki/Alfredo_el_Grande'],
    body: 'Rey de Wessex (871-899) que detuvo el avance vikingo en Inglaterra y consolidó las bases del reino anglosajón unificado por su nieto Athelstan en 927.' },
  { id: 'isabel-i-de-inglaterra', name: 'Isabel I de Inglaterra', name_en: 'Elizabeth I', year_born: 1533, year_died: 1603,
    polity: ['reino-de-inglaterra'], region: 'europa', role: 'politico', tags: ['reina', 'reina-virgen', 'tudor'],
    sources: ['https://es.wikipedia.org/wiki/Isabel_I_de_Inglaterra'],
    body: 'Reina de Inglaterra e Irlanda (1558-1603), última de la dinastía Tudor. Apogeo cultural isabelino (Shakespeare). Derrotó la Armada española (1588) consolidando la independencia anglicana.' },
  { id: 'isaac-newton', name: 'Isaac Newton', name_en: 'Isaac Newton', year_born: 1643, year_died: 1727,
    polity: ['reino-de-inglaterra'], region: 'europa', role: 'cientifico', tags: ['fisica', 'matematicas', 'optica'],
    wikidata: 'Q935',
    sources: ['https://es.wikipedia.org/wiki/Isaac_Newton'],
    body: 'Físico, matemático y astrónomo inglés. Sus Principia Mathematica (1687) formularon las leyes del movimiento y la gravitación universal — base de la mecánica clásica.' },
  { id: 'william-shakespeare', name: 'William Shakespeare', name_en: 'William Shakespeare', year_born: 1564, year_died: 1616,
    polity: ['reino-de-inglaterra'], region: 'europa', role: 'artista', tags: ['dramaturgo', 'isabelino'],
    wikidata: 'Q692',
    sources: ['https://es.wikipedia.org/wiki/William_Shakespeare'],
    body: 'Dramaturgo y poeta inglés del periodo isabelino. 37 obras (Hamlet, Macbeth, Lear, Otelo, Romeo y Julieta) y 154 sonetos que reconfiguraron el inglés literario.' },
  { id: 'juana-de-arco', name: 'Juana de Arco', name_en: 'Joan of Arc', year_born: 1412, year_died: 1431,
    polity: ['reino-de-francia'], region: 'europa', role: 'militar', tags: ['santa', 'doncella-orleans'],
    sources: ['https://es.wikipedia.org/wiki/Juana_de_Arco'],
    body: 'Campesina lorenesa que afirmó tener visiones divinas y lideró el ejército francés en la Guerra de los Cien Años. Levantó el sitio de Orleans (1429); capturada y quemada por herejía a los 19.' },
  { id: 'luis-xiv-de-francia', name: 'Luis XIV de Francia', name_en: 'Louis XIV', year_born: 1638, year_died: 1715,
    polity: ['reino-de-francia'], region: 'europa', role: 'politico', tags: ['rey-sol', 'absolutismo', 'borbon'],
    sources: ['https://es.wikipedia.org/wiki/Luis_XIV_de_Francia'],
    body: 'Rey de Francia durante 72 años (1643-1715) — el reinado más largo documentado de Europa. "El Estado soy yo": absolutismo paradigmático, Versalles, guerras europeas casi continuas.' },
  { id: 'voltaire', name: 'Voltaire', name_en: 'Voltaire', year_born: 1694, year_died: 1778,
    polity: ['reino-de-francia'], region: 'europa', role: 'filosofo', tags: ['ilustracion', 'satira'],
    sources: ['https://es.wikipedia.org/wiki/Voltaire'],
    body: 'Filósofo y escritor francés, figura central de la Ilustración. Defensor de la libertad de expresión, la tolerancia religiosa y la separación Iglesia-Estado. Cándido (1759) es su sátira más leída.' },
  { id: 'isabel-i-de-castilla', name: 'Isabel I de Castilla', name_en: 'Isabella I of Castile', year_born: 1451, year_died: 1504,
    polity: ['imperio-espanol'], region: 'europa', role: 'politico', tags: ['reina', 'reyes-catolicos'],
    sources: ['https://es.wikipedia.org/wiki/Isabel_I_de_Castilla'],
    body: 'Reina de Castilla (1474-1504) y co-monarca con Fernando II de Aragón ("Reyes Católicos"). Auspició el viaje de Colón (1492), completó la Reconquista con Granada y expulsó a los judíos.' },
  { id: 'felipe-ii-de-espana', name: 'Felipe II de España', name_en: 'Philip II of Spain', year_born: 1527, year_died: 1598,
    polity: ['imperio-espanol'], region: 'europa', role: 'politico', tags: ['rey', 'habsburgo', 'contrareforma'],
    sources: ['https://es.wikipedia.org/wiki/Felipe_II_de_España'],
    body: 'Rey de España (1556-1598) en la cúspide del imperio: España, Portugal (1580), Países Bajos, Italia, América, Filipinas. Lidero la Contrarreforma católica; el desastre de la Armada Invencible (1588) marcó el inicio del declive.' },
  { id: 'miguel-de-cervantes', name: 'Miguel de Cervantes', name_en: 'Miguel de Cervantes', year_born: 1547, year_died: 1616,
    polity: ['imperio-espanol'], region: 'europa', role: 'artista', tags: ['novelista', 'siglo-de-oro'],
    sources: ['https://es.wikipedia.org/wiki/Miguel_de_Cervantes'],
    body: 'Soldado y escritor español del Siglo de Oro. Don Quijote de la Mancha (1605, 1615) es considerado la primera novela moderna y una de las obras pivotales de la literatura mundial.' },
  { id: 'ivan-iv-el-terrible', name: 'Iván IV el Terrible', name_en: 'Ivan the Terrible', year_born: 1530, year_died: 1584,
    polity: ['imperio-ruso'], region: 'europa', role: 'politico', tags: ['zar', 'expansion-territorial'],
    sources: ['https://es.wikipedia.org/wiki/Iván_IV_de_Rusia'],
    body: 'Primer monarca ruso en titularse Zar (1547). Centralizó el poder mediante la oprichnina (policía-terror), conquistó Kazán, Astracán y partes de Siberia. Su reinado quedó como sinónimo de autocracia brutal.' },
  { id: 'pedro-i-el-grande', name: 'Pedro I el Grande', name_en: 'Peter the Great', year_born: 1672, year_died: 1725,
    polity: ['imperio-ruso'], region: 'europa', role: 'politico', tags: ['zar', 'occidentalizacion'],
    sources: ['https://es.wikipedia.org/wiki/Pedro_I_de_Rusia'],
    body: 'Zar (1682-1725) que occidentalizó Rusia: fundó San Petersburgo (1703), reformó ejército y marina, importó tecnología y costumbres europeas. Proclamó el Imperio Ruso (1721).' },

  // ─── Medio Oriente (17) ─────────────────────────────────────────────────
  { id: 'hammurabi', name: 'Hammurabi', name_en: 'Hammurabi', year_born: -1810, year_died: -1750,
    polity: ['babilonia'], region: 'medio-oriente', role: 'politico', tags: ['rey', 'codigo-legal'],
    sources: ['https://es.wikipedia.org/wiki/Hammurabi'],
    body: 'Sexto rey de Babilonia (1792-1750 BCE). Promulgó el Código de Hammurabi (~1754 BCE) — uno de los primeros corpus legales documentados, con sus 282 leyes inscritas en una estela de basalto hoy en el Louvre.' },
  { id: 'nabucodonosor-ii', name: 'Nabucodonosor II', name_en: 'Nebuchadnezzar II', year_born: -642, year_died: -562,
    polity: ['babilonia'], region: 'medio-oriente', role: 'politico', tags: ['rey', 'caldeo'],
    sources: ['https://es.wikipedia.org/wiki/Nabucodonosor_II'],
    body: 'Rey de la dinastía neo-babilónica (605-562 BCE). Destruyó Jerusalén (587 BCE) iniciando el exilio judío. Constructor de los Jardines Colgantes (debatido) y de la Puerta de Ishtar.' },
  { id: 'ciro-el-grande', name: 'Ciro el Grande', name_en: 'Cyrus the Great', year_born: -600, year_died: -530,
    polity: ['imperio-persa-aquemenida'], region: 'medio-oriente', role: 'politico', tags: ['rey', 'fundador'],
    sources: ['https://es.wikipedia.org/wiki/Ciro_II_el_Grande'],
    body: 'Fundador del Imperio Aqueménida (550 BCE). Conquistó Lidia, Babilonia y Media. Su Cilindro de Ciro (~539 BCE) es citado como precursor de los derechos humanos por su tolerancia religiosa.' },
  { id: 'dario-i', name: 'Darío I', name_en: 'Darius I', year_born: -550, year_died: -486,
    polity: ['imperio-persa-aquemenida'], region: 'medio-oriente', role: 'politico', tags: ['rey', 'organizador'],
    sources: ['https://es.wikipedia.org/wiki/Darío_I'],
    body: 'Rey aqueménida (522-486 BCE) en la mayor extensión del imperio. Organizó las satrapías, estandarizó pesos y medidas, construyó Persépolis. Derrotado por los griegos en Maratón (490 BCE).' },
  { id: 'jerjes-i', name: 'Jerjes I', name_en: 'Xerxes I', year_born: -519, year_died: -465,
    polity: ['imperio-persa-aquemenida'], region: 'medio-oriente', role: 'politico', tags: ['rey', 'guerras-medicas'],
    sources: ['https://es.wikipedia.org/wiki/Jerjes_I'],
    body: 'Hijo de Darío, rey aqueménida (486-465 BCE). Lideró la Segunda Guerra Médica contra Grecia: cruzó el Helesponto con un ejército masivo, ganó Termópilas, pero fue derrotado en Salamina y Platea.' },
  { id: 'zaratustra', name: 'Zaratustra', name_en: 'Zarathustra / Zoroaster', year_born: -1000, year_died: -930,
    polity: [], region: 'medio-oriente', role: 'religioso', tags: ['profeta', 'fundador-religion'],
    sources: ['https://es.wikipedia.org/wiki/Zaratustra'],
    body: 'Profeta persa fundador del zoroastrismo. Predicó el dualismo cósmico Ahura Mazda vs. Angra Mainyu y la responsabilidad ética individual. Datación incierta (entre -1500 y -600 BCE).' },
  { id: 'ardashir-i', name: 'Ardashir I', name_en: 'Ardashir I', year_born: 180, year_died: 242,
    polity: ['imperio-sasanida'], region: 'medio-oriente', role: 'politico', tags: ['shahanshah', 'fundador-sasanida'],
    sources: ['https://es.wikipedia.org/wiki/Ardacher_I'],
    body: 'Fundador del Imperio Sasánida tras derrotar a los partos (224 CE). Restableció el zoroastrismo como religión estatal y se autoproclamó "Rey de Reyes" reivindicando continuidad aqueménida.' },
  { id: 'cosroes-i', name: 'Cosroes I', name_en: 'Khosrow I', year_born: 501, year_died: 579,
    polity: ['imperio-sasanida'], region: 'medio-oriente', role: 'politico', tags: ['shahanshah', 'reformador'],
    sources: ['https://es.wikipedia.org/wiki/Cosroes_I'],
    body: 'Sah sasánida (531-579), uno de los más célebres de la dinastía. Reformó tributación y ejército, patrocinó traducciones del sánscrito y griego, fundó la academia de Gondishapur — centro intelectual pre-islámico clave.' },
  { id: 'jesus-de-nazaret', name: 'Jesús de Nazaret', name_en: 'Jesus of Nazareth', year_born: -4, year_died: 30,
    polity: [], region: 'medio-oriente', role: 'religioso', tags: ['profeta', 'fundador-religion'],
    wikidata: 'Q302',
    sources: ['https://es.wikipedia.org/wiki/Jesús_de_Nazaret'],
    body: 'Predicador judío de Galilea cuya enseñanza y muerte/resurrección según la tradición dieron origen al cristianismo. Su biografía histórica es discutida; ejecutado por crucifixión bajo Poncio Pilato (~30 CE).' },
  { id: 'mahoma', name: 'Mahoma', name_en: 'Muhammad', year_born: 570, year_died: 632,
    polity: [], region: 'medio-oriente', role: 'religioso', tags: ['profeta', 'fundador-islam'],
    sources: ['https://es.wikipedia.org/wiki/Mahoma'],
    body: 'Profeta del islam según la tradición musulmana. Sus revelaciones (recogidas en el Corán) y su Hégira de Meca a Medina (622 CE) marcan el inicio del calendario islámico. Para su muerte había unificado políticamente la mayor parte de Arabia.' },
  { id: 'harun-al-rashid', name: 'Harún al-Rashid', name_en: 'Harun al-Rashid', year_born: 763, year_died: 809,
    polity: ['califato-abasi'], region: 'medio-oriente', role: 'politico', tags: ['califa', 'edad-de-oro'],
    sources: ['https://es.wikipedia.org/wiki/Harún_al-Rashid'],
    body: 'Quinto califa abasí (786-809), apogeo cultural islámico. Patrocinó la Casa de la Sabiduría. Su figura legendaria aparece en Las mil y una noches; correspondió con Carlomagno.' },
  { id: 'al-juarismi', name: 'Al-Juarismi', name_en: 'al-Khwarizmi', year_born: 780, year_died: 850,
    polity: ['califato-abasi'], region: 'medio-oriente', role: 'cientifico', tags: ['matematico', 'algebra'],
    sources: ['https://es.wikipedia.org/wiki/Al-Juarismi'],
    body: 'Matemático persa de la Casa de la Sabiduría en Bagdad. Su libro Al-Kitab al-Mukhtaṣar fī Ḥisāb al-Jabr wa-l-Muqābala dio nombre al "álgebra"; introdujo los numerales hindúes en el mundo islámico.' },
  { id: 'avicena', name: 'Avicena (Ibn Sina)', name_en: 'Avicenna (Ibn Sina)', year_born: 980, year_died: 1037,
    polity: ['califato-abasi'], region: 'medio-oriente', role: 'filosofo', tags: ['medicina', 'metafisica'],
    sources: ['https://es.wikipedia.org/wiki/Avicena'],
    body: 'Polimata persa, su Canon de la Medicina fue el manual médico estándar en Europa hasta el siglo XVII. Sintetizó filosofía aristotélica con teología islámica; influyó tanto a Maimónides como a Tomás de Aquino.' },
  { id: 'mehmed-ii', name: 'Mehmed II', name_en: 'Mehmed II the Conqueror', year_born: 1432, year_died: 1481,
    polity: ['imperio-otomano'], region: 'medio-oriente', role: 'politico', tags: ['sultan', 'conquistador-constantinopla'],
    sources: ['https://es.wikipedia.org/wiki/Mehmed_II'],
    body: 'Séptimo sultán otomano. Conquistó Constantinopla en 1453 a los 21 años, poniendo fin al Imperio Bizantino y consolidando Estambul como capital del nuevo imperio islámico mediterráneo-balcánico.' },
  { id: 'suleiman-el-magnifico', name: 'Solimán el Magnífico', name_en: 'Suleiman the Magnificent', year_born: 1494, year_died: 1566,
    polity: ['imperio-otomano'], region: 'medio-oriente', role: 'politico', tags: ['sultan', 'apogeo'],
    sources: ['https://es.wikipedia.org/wiki/Solimán_el_Magnífico'],
    body: 'Décimo sultán otomano (1520-1566), apogeo territorial y cultural del imperio. Conquistó Belgrado, Rodas, Hungría, parte de Persia y el norte de África. Reformador legal (el sobrenombre "Kanuni" = legislador).' },
  { id: 'mimar-sinan', name: 'Mimar Sinan', name_en: 'Mimar Sinan', year_born: 1489, year_died: 1588,
    polity: ['imperio-otomano'], region: 'medio-oriente', role: 'artista', tags: ['arquitecto', 'mezquitas'],
    sources: ['https://es.wikipedia.org/wiki/Mimar_Sinán'],
    body: 'Arquitecto jefe del sultán Solimán y sus sucesores. Diseñó más de 300 estructuras, entre ellas la mezquita Süleymaniye de Estambul y la Selimiye de Edirne — cumbres de la arquitectura otomana.' },

  // ─── Norte de África (7) ────────────────────────────────────────────────
  { id: 'ramses-ii', name: 'Ramsés II', name_en: 'Ramesses II', year_born: -1303, year_died: -1213,
    polity: ['egipto-faraonico'], region: 'norte-africa', role: 'politico', tags: ['faraon', 'imperio-nuevo'],
    sources: ['https://es.wikipedia.org/wiki/Ramsés_II'],
    body: 'Faraón de la dinastía XIX (1279-1213 BCE) — el "Grande". Reinado de 66 años, batalla de Kadesh contra los hititas (1274 BCE), primer tratado de paz internacional documentado. Constructor prolífico: Abu Simbel, Ramesseum.' },
  { id: 'hatshepsut', name: 'Hatshepsut', name_en: 'Hatshepsut', year_born: -1507, year_died: -1458,
    polity: ['egipto-faraonico'], region: 'norte-africa', role: 'politico', tags: ['faraona', 'dinastia-xviii'],
    sources: ['https://es.wikipedia.org/wiki/Hatshepsut'],
    body: 'Faraona de la dinastía XVIII (1479-1458 BCE), una de las muy pocas mujeres en gobernar Egipto con plenos atributos faraónicos. Promovió rutas comerciales hacia Punt y un templo mortuorio espectacular en Deir el-Bahari.' },
  { id: 'akenaton', name: 'Akenatón', name_en: 'Akhenaten', year_born: -1380, year_died: -1336,
    polity: ['egipto-faraonico'], region: 'norte-africa', role: 'politico', tags: ['faraon', 'monoteismo-atonista'],
    sources: ['https://es.wikipedia.org/wiki/Akenatón'],
    body: 'Faraón de la dinastía XVIII (1353-1336 BCE) que intentó imponer el monoteísmo de Atón, fundó la ciudad de Amarna y disrumpió el panteón tradicional. Sus sucesores (incluyendo Tutankamón) revirtieron sus reformas.' },
  { id: 'cleopatra-vii', name: 'Cleopatra VII', name_en: 'Cleopatra VII', year_born: -69, year_died: -30,
    polity: ['egipto-faraonico', 'macedonia-helenistica'], region: 'norte-africa', role: 'politico', tags: ['reina', 'ptolemaica', 'ultima-faraona'],
    sources: ['https://es.wikipedia.org/wiki/Cleopatra'],
    body: 'Última faraona del Egipto ptolemaico (51-30 BCE). Alianzas con Julio César y Marco Antonio en su intento de preservar la independencia egipcia frente a Roma. Tras la derrota de Actium se suicidó; Egipto se convirtió en provincia romana.' },
  { id: 'piye', name: 'Piye', name_en: 'Piye', year_born: -780, year_died: -714,
    polity: ['reino-de-kush'], region: 'norte-africa', role: 'politico', tags: ['rey', 'fundador-dinastia-xxv'],
    sources: ['https://es.wikipedia.org/wiki/Pianjy'],
    body: 'Rey nubio del reino de Kush que conquistó Egipto (~744 BCE) fundando la dinastía XXV egipcia ("faraones negros"). Su estela de la victoria es uno de los textos jeroglíficos más extensos del Egipto tardío.' },
  { id: 'al-muizz-li-din-allah', name: "Al-Mu'izz li-Din Allah", name_en: "Al-Mu'izz li-Din Allah", year_born: 932, year_died: 975,
    polity: ['califato-fatimi'], region: 'norte-africa', role: 'politico', tags: ['califa', 'ismaili', 'fundador-cairo'],
    sources: ['https://es.wikipedia.org/wiki/Al-Muizz_li-Din_Allah'],
    body: 'Cuarto califa fatimí (953-975). Bajo su mando los fatimíes conquistaron Egipto (969) y fundaron El Cairo como nueva capital. Estableció la mezquita-universidad de Al-Azhar, aún operando.' },
  { id: 'ibn-al-haytham', name: 'Ibn al-Haytham (Alhacén)', name_en: 'Ibn al-Haytham (Alhazen)', year_born: 965, year_died: 1040,
    polity: ['califato-fatimi'], region: 'norte-africa', role: 'cientifico', tags: ['optica', 'metodo-experimental'],
    sources: ['https://es.wikipedia.org/wiki/Alhacén'],
    body: 'Polimata árabe en El Cairo fatimí. Su Kitab al-Manazir (Tratado de Óptica, ~1021) revolucionó la óptica al rechazar la teoría de la emisión visual y formular el método experimental — siglos antes de la Revolución Científica europea.' },

  // ─── África Sub-Sahariana (8) ───────────────────────────────────────────
  { id: 'ezana-de-aksum', name: 'Ezana de Aksum', name_en: 'Ezana of Axum', year_born: 320, year_died: 360,
    polity: ['imperio-aksum'], region: 'africa-subsahariana', role: 'politico', tags: ['rey', 'cristianizacion'],
    sources: ['https://es.wikipedia.org/wiki/Ezana_de_Aksum'],
    body: 'Rey del Imperio de Aksum (~330-360 CE) que adoptó el cristianismo como religión estatal, convirtiendo a Aksum en el segundo estado cristiano oficial tras Armenia. Conquistó el reino de Kush.' },
  { id: 'sundiata-keita', name: 'Sundiata Keita', name_en: 'Sundiata Keita', year_born: 1217, year_died: 1255,
    polity: ['imperio-mali'], region: 'africa-subsahariana', role: 'politico', tags: ['mansa', 'fundador'],
    sources: ['https://es.wikipedia.org/wiki/Sundiata_Keita'],
    body: 'Fundador del Imperio de Malí tras derrotar al rey Sumaoro Kanté en la batalla de Kirina (1235). Promulgó la Carta de Mandén/Kurukan Fuga, considerada una de las primeras declaraciones de derechos humanos.' },
  { id: 'mansa-musa', name: 'Mansa Musa', name_en: 'Mansa Musa', year_born: 1280, year_died: 1337,
    polity: ['imperio-mali'], region: 'africa-subsahariana', role: 'politico', tags: ['mansa', 'oro', 'hayy'],
    sources: ['https://es.wikipedia.org/wiki/Mansa_Musa'],
    body: 'Décimo mansa del Imperio de Malí (1312-1337), referido a menudo como el hombre más rico de la historia documentada. Su peregrinación a La Meca (1324) cruzando Egipto provocó inflación duradera en El Cairo por la cantidad de oro que repartió.' },
  { id: 'askia-mohammad-i', name: 'Askia Mohammad I', name_en: 'Askia Mohammad I', year_born: 1442, year_died: 1538,
    polity: ['imperio-songhai'], region: 'africa-subsahariana', role: 'politico', tags: ['askia', 'islam', 'reformador'],
    sources: ['https://es.wikipedia.org/wiki/Askia_Mohammad_I'],
    body: 'Emperador del Songhai (1493-1528). Reformó administración, ejército y estructura tributaria, e impulsó Tombuctú como centro intelectual islámico. Hizo peregrinación a La Meca con 300,000 piezas de oro.' },
  { id: 'afonso-i-del-kongo', name: 'Afonso I del Kongo', name_en: 'Afonso I of Kongo', year_born: 1456, year_died: 1542,
    polity: ['reino-del-kongo'], region: 'africa-subsahariana', role: 'politico', tags: ['rey', 'cristianismo', 'manikongo'],
    sources: ['https://es.wikipedia.org/wiki/Afonso_I_del_Congo'],
    body: 'Rey cristiano del Kongo (1509-1542), bautizado tras la conversión voluntaria de su padre. Mantuvo correspondencia con el papa y la corona portuguesa, intentando frenar la trata de esclavos atlántica que ya devastaba su reino.' },
  { id: 'ewuare-i-de-benin', name: 'Ewuare I de Benín', name_en: 'Ewuare I of Benin', year_born: 1400, year_died: 1473,
    polity: ['reino-de-benin'], region: 'africa-subsahariana', role: 'politico', tags: ['oba', 'fundador-imperio'],
    sources: ['https://es.wikipedia.org/wiki/Ewuare_el_Grande'],
    body: 'Oba (rey) del reino de Benín (~1440-1473). Transformó la ciudad-estado en un imperio expansivo; rodeó la capital con murallas y fosos; estableció instituciones cortesanas e impulsó el arte del bronce.' },
  { id: 'ahmed-baba-de-tombuctu', name: 'Ahmed Baba de Tombuctú', name_en: 'Ahmed Baba al-Massufi', year_born: 1556, year_died: 1627,
    polity: ['imperio-songhai'], region: 'africa-subsahariana', role: 'filosofo', tags: ['jurista', 'sankore'],
    sources: ['https://es.wikipedia.org/wiki/Ahmad_Baba_al-Massufi'],
    body: 'Polímata islámico de Tombuctú, profesor en la universidad de Sankoré. Autor de unas 60 obras de derecho, gramática y biografía. Deportado a Marruecos tras la conquista del Songhai (1591); su biblioteca personal fue saqueada.' },
  { id: 'reina-nzinga-mbande', name: 'Reina Nzinga Mbande', name_en: 'Queen Nzinga Mbande', year_born: 1583, year_died: 1663,
    polity: [], region: 'africa-subsahariana', role: 'politico', tags: ['reina', 'resistencia-portuguesa', 'ndongo-matamba'],
    sources: ['https://es.wikipedia.org/wiki/Nzinga_de_Ndongo_y_Matamba'],
    body: 'Reina de Ndongo y Matamba (actual Angola), figura central de la resistencia africana al colonialismo portugués durante 4 décadas. Negoció como par con los portugueses, formó alianzas con holandeses, y luchó hasta los 80 años.' },

  // ─── Sur de Asia (15) ───────────────────────────────────────────────────
  { id: 'siddharta-gautama', name: 'Siddhartha Gautama (Buda)', name_en: 'Siddhartha Gautama (Buddha)', year_born: -563, year_died: -483,
    polity: [], region: 'sur-asia', role: 'religioso', tags: ['fundador-budismo', 'principe-renunciante'],
    sources: ['https://es.wikipedia.org/wiki/Buda_Gautama'],
    body: 'Príncipe del clan Shakya en la región del Nepal/India actual. Renunció a la vida palatina y, tras alcanzar la iluminación bajo el árbol Bodhi, fundó el budismo predicando las Cuatro Nobles Verdades durante 45 años.' },
  { id: 'mahavira', name: 'Mahavira', name_en: 'Mahavira', year_born: -599, year_died: -527,
    polity: [], region: 'sur-asia', role: 'religioso', tags: ['fundador-jainismo', 'tirthankara'],
    sources: ['https://es.wikipedia.org/wiki/Mahavira'],
    body: '24º y último Tirthankara según la tradición jaina, contemporáneo de Buda. Reformuló el jainismo enfatizando los cinco grandes votos (ahimsa, satya, asteya, brahmacharya, aparigraha).' },
  { id: 'panini', name: 'Panini', name_en: 'Pāṇini', year_born: -520, year_died: -460,
    polity: [], region: 'sur-asia', role: 'filosofo', tags: ['gramatica', 'sanscrito'],
    sources: ['https://es.wikipedia.org/wiki/Panini_(gramático)'],
    body: 'Gramático del sánscrito que en su Ashtadhyayi codificó la lengua en ~4,000 sutras altamente formales. Su obra anticipa por dos milenios formalismos de la lingüística computacional moderna.' },
  { id: 'chandragupta-maurya', name: 'Chandragupta Maurya', name_en: 'Chandragupta Maurya', year_born: -340, year_died: -297,
    polity: ['imperio-maurya'], region: 'sur-asia', role: 'politico', tags: ['fundador', 'emperador'],
    sources: ['https://es.wikipedia.org/wiki/Chandragupta_Maurya'],
    body: 'Fundador del Imperio Maurya (322 BCE), unificó casi todo el subcontinente indio asesorado por el estratega Chanakya (autor del Arthashastra). Abdicó en la vejez y se convirtió al jainismo.' },
  { id: 'ashoka', name: 'Ashoka el Grande', name_en: 'Ashoka the Great', year_born: -304, year_died: -232,
    polity: ['imperio-maurya'], region: 'sur-asia', role: 'politico', tags: ['emperador', 'budismo', 'dhamma'],
    sources: ['https://es.wikipedia.org/wiki/Aśoka'],
    body: 'Nieto de Chandragupta Maurya. Tras la sangrienta conquista de Kalinga (~261 BCE) se convirtió al budismo y propagó el dhamma con misiones a Sri Lanka, Asia Central y el Mediterráneo. Sus edictos en pilares de piedra son los textos epigráficos más extensos del subcontinente.' },
  { id: 'chandragupta-i-gupta', name: 'Chandragupta I (Gupta)', name_en: 'Chandragupta I (Gupta)', year_born: 280, year_died: 335,
    polity: ['imperio-gupta'], region: 'sur-asia', role: 'politico', tags: ['emperador', 'fundador-gupta'],
    sources: ['https://es.wikipedia.org/wiki/Chandragupta_I'],
    body: 'Fundador del Imperio Gupta (~320 CE), centralizó el norte de la India tras siglos de fragmentación post-Maurya. Su matrimonio con la princesa licchavi consolidó alianzas en el valle del Ganges.' },
  { id: 'samudragupta', name: 'Samudragupta', name_en: 'Samudragupta', year_born: 320, year_died: 380,
    polity: ['imperio-gupta'], region: 'sur-asia', role: 'politico', tags: ['emperador', 'conquistador'],
    sources: ['https://es.wikipedia.org/wiki/Samudragupta'],
    body: 'Hijo y sucesor de Chandragupta I, conocido como el "Napoleón indio". Conquistó gran parte del subcontinente. Su columna en Allahabad detalla 21 reinos sometidos.' },
  { id: 'kalidasa', name: 'Kalidasa', name_en: 'Kālidāsa', year_born: 350, year_died: 460,
    polity: ['imperio-gupta'], region: 'sur-asia', role: 'artista', tags: ['poeta', 'dramaturgo', 'sanscrito'],
    sources: ['https://es.wikipedia.org/wiki/Kalidasa'],
    body: 'Poeta y dramaturgo en sánscrito de la corte Gupta. Su drama Abhijñānaśākuntalam y su poema Meghadūta son cimas del clasicismo indio. Goethe lo admiraba.' },
  { id: 'aryabhata', name: 'Aryabhata', name_en: 'Aryabhata', year_born: 476, year_died: 550,
    polity: ['imperio-gupta'], region: 'sur-asia', role: 'cientifico', tags: ['matematico', 'astronomo'],
    sources: ['https://es.wikipedia.org/wiki/Aryabhatá'],
    body: 'Astrónomo y matemático del periodo Gupta. Su Aryabhatiya (~499 CE) trabaja con sistema decimal posicional, da una aproximación de π de 4 decimales, calcula la duración del año solar con error de pocos minutos, y propone (siglos antes que Copérnico) la rotación de la Tierra.' },
  { id: 'rajaraja-chola-i', name: 'Rajaraja Chola I', name_en: 'Rajaraja Chola I', year_born: 947, year_died: 1014,
    polity: ['imperio-chola'], region: 'sur-asia', role: 'politico', tags: ['rey', 'naval', 'templos'],
    sources: ['https://es.wikipedia.org/wiki/Rajaraja_Chola_I'],
    body: 'Emperador chola (985-1014) que expandió el imperio a Sri Lanka, Maldivas y partes del sudeste asiático. Construyó el monumental templo Brihadeeswara en Thanjavur.' },
  { id: 'rajendra-chola-i', name: 'Rajendra Chola I', name_en: 'Rajendra Chola I', year_born: 971, year_died: 1044,
    polity: ['imperio-chola'], region: 'sur-asia', role: 'militar', tags: ['expedicion-srivijaya', 'naval'],
    sources: ['https://es.wikipedia.org/wiki/Rajendra_Chola_I'],
    body: 'Hijo de Rajaraja, llevó la proyección naval chola a su máxima extensión. Su expedición naval contra Srivijaya (~1025) atacó territorios en Sumatra y Java — campaña marítima sin paralelo en la historia india.' },
  { id: 'babur', name: 'Babur', name_en: 'Babur', year_born: 1483, year_died: 1530,
    polity: ['imperio-mogol'], region: 'sur-asia', role: 'politico', tags: ['emperador', 'fundador-mogol', 'timurida'],
    sources: ['https://es.wikipedia.org/wiki/Babur'],
    body: 'Descendiente timúrida y genghiskhánida que fundó el Imperio Mogol tras vencer al sultán de Delhi en la batalla de Panipat (1526). Su autobiografía Baburnama es una obra clásica de las memorias islámicas.' },
  { id: 'akbar', name: 'Akbar el Grande', name_en: 'Akbar the Great', year_born: 1542, year_died: 1605,
    polity: ['imperio-mogol'], region: 'sur-asia', role: 'politico', tags: ['emperador', 'sincretismo', 'apogeo'],
    sources: ['https://es.wikipedia.org/wiki/Akbar_I'],
    body: 'Tercer emperador mogol (1556-1605), apogeo del imperio. Política religiosa sincrética (din-i-ilahi), abolición del impuesto jizya a no musulmanes, alianzas con rajputs hindúes, integración hindú-musulmana en la administración.' },
  { id: 'shah-jahan', name: 'Shah Jahan', name_en: 'Shah Jahan', year_born: 1592, year_died: 1666,
    polity: ['imperio-mogol'], region: 'sur-asia', role: 'politico', tags: ['emperador', 'taj-mahal', 'arquitectura'],
    sources: ['https://es.wikipedia.org/wiki/Shah_Jahan'],
    body: 'Quinto emperador mogol (1628-1658). Conocido principalmente por construir el Taj Mahal como mausoleo para su esposa Mumtaz. Depuesto y encarcelado por su hijo Aurangzeb.' },
  { id: 'aurangzeb', name: 'Aurangzeb', name_en: 'Aurangzeb', year_born: 1618, year_died: 1707,
    polity: ['imperio-mogol'], region: 'sur-asia', role: 'politico', tags: ['emperador', 'ortodoxia-islamica', 'maxima-extension'],
    sources: ['https://es.wikipedia.org/wiki/Aurangzeb'],
    body: 'Sexto y último gran emperador mogol (1658-1707). Logró la máxima extensión territorial del imperio incluyendo el sur de la India. Retorno a la ortodoxia sunita (reinstaurando jizya, prohibiendo música cortesana) que tensó las relaciones hindú-musulmanas y aceleró el declive imperial.' },

  // ─── Este de Asia (24) ──────────────────────────────────────────────────
  { id: 'confucio', name: 'Confucio', name_en: 'Confucius', year_born: -551, year_died: -479,
    polity: [], region: 'este-asia', role: 'filosofo', tags: ['fundador-confucianismo', 'maestro'],
    wikidata: 'Q4604',
    sources: ['https://es.wikipedia.org/wiki/Confucio'],
    body: 'Maestro y filósofo del estado de Lu durante la dinastía Zhou tardía. Sus enseñanzas, recopiladas en las Analectas por sus discípulos, establecieron las bases del confucianismo: ren, li, xiao, y el ideal del junzi.' },
  { id: 'laozi', name: 'Laozi', name_en: 'Laozi', year_born: -571, year_died: -471,
    polity: [], region: 'este-asia', role: 'filosofo', tags: ['fundador-daoismo', 'dao-de-jing'],
    sources: ['https://es.wikipedia.org/wiki/Lao-Tse'],
    body: 'Sabio chino legendario autor del Dao De Jing (~6º BCE, datación debatida). Su historicidad es discutida; el texto fundacional del daoísmo presenta la práctica del wu wei (acción sin esfuerzo) y la armonía con el Dao.' },
  { id: 'liu-bang', name: 'Liu Bang (Gaozu)', name_en: 'Liu Bang (Emperor Gaozu)', year_born: -256, year_died: -195,
    polity: ['dinastia-han'], region: 'este-asia', role: 'politico', tags: ['emperador', 'fundador-han'],
    sources: ['https://es.wikipedia.org/wiki/Gaozu_de_Han'],
    body: 'Fundador de la dinastía Han (202 BCE), de origen campesino. Derrotó a Xiang Yu en la guerra Chu-Han que siguió a la caída de Qin. Estableció el modelo institucional Han basado en confucianismo administrativo.' },
  { id: 'wu-di-de-han', name: 'Emperador Wu de Han', name_en: 'Emperor Wu of Han', year_born: -156, year_died: -87,
    polity: ['dinastia-han'], region: 'este-asia', role: 'politico', tags: ['emperador', 'expansion-territorial', 'confucianismo'],
    sources: ['https://es.wikipedia.org/wiki/Emperador_Wu_de_Han'],
    body: 'Séptimo emperador Han (141-87 BCE). Adoptó el confucianismo como ideología estatal, expandió el imperio hacia Asia Central (abriendo la Ruta de la Seda), Vietnam y Corea. Largo reinado de 54 años.' },
  { id: 'sima-qian', name: 'Sima Qian', name_en: 'Sima Qian', year_born: -145, year_died: -86,
    polity: ['dinastia-han'], region: 'este-asia', role: 'artista', tags: ['historiador', 'shiji'],
    sources: ['https://es.wikipedia.org/wiki/Sima_Qian'],
    body: 'Historiador del emperador Wu, autor del Shiji ("Registros del Gran Historiador"), historia universal de China desde los inicios míticos hasta su época — modelo para toda la historiografía oficial china posterior.' },
  { id: 'li-shimin', name: 'Li Shimin (Tang Taizong)', name_en: 'Emperor Taizong of Tang', year_born: 599, year_died: 649,
    polity: ['dinastia-tang'], region: 'este-asia', role: 'politico', tags: ['emperador', 'apogeo-tang'],
    sources: ['https://es.wikipedia.org/wiki/Emperador_Taizong_de_Tang'],
    body: 'Segundo emperador Tang (626-649), su reinado (era Zhenguan) es considerado el modelo de buen gobierno en la tradición confuciana. Expandió el imperio hacia Asia Central y Corea.' },
  { id: 'wu-zetian', name: 'Wu Zetian', name_en: 'Wu Zetian', year_born: 624, year_died: 705,
    polity: ['dinastia-tang'], region: 'este-asia', role: 'politico', tags: ['emperatriz', 'unica-emperatriz-china'],
    sources: ['https://es.wikipedia.org/wiki/Wu_Zetian'],
    body: 'Única mujer en la historia china en gobernar como emperatriz con título imperial pleno (690-705). Brevemente interrumpió la dinastía Tang con su propia dinastía Zhou. Promovió el budismo y los exámenes imperiales.' },
  { id: 'li-bai', name: 'Li Bai', name_en: 'Li Bai', year_born: 701, year_died: 762,
    polity: ['dinastia-tang'], region: 'este-asia', role: 'artista', tags: ['poeta', 'taoismo'],
    sources: ['https://es.wikipedia.org/wiki/Li_Bai'],
    body: 'Poeta de la dinastía Tang, considerado junto a Du Fu uno de los dos grandes maestros poéticos chinos. Espíritu daoísta, romántico, dado al vino; sus ~1,000 poemas conservados son canon literario chino.' },
  { id: 'du-fu', name: 'Du Fu', name_en: 'Du Fu', year_born: 712, year_died: 770,
    polity: ['dinastia-tang'], region: 'este-asia', role: 'artista', tags: ['poeta', 'confuciano'],
    sources: ['https://es.wikipedia.org/wiki/Du_Fu'],
    body: 'Poeta Tang contemporáneo y amigo de Li Bai. Su poesía, más confuciana y socialmente comprometida, atestigua la rebelión de An Lushan (755) y la decadencia del apogeo Tang.' },
  { id: 'xuanzang', name: 'Xuanzang', name_en: 'Xuanzang', year_born: 602, year_died: 664,
    polity: ['dinastia-tang'], region: 'este-asia', role: 'religioso', tags: ['monje', 'peregrino', 'budismo'],
    sources: ['https://es.wikipedia.org/wiki/Xuanzang'],
    body: 'Monje budista que viajó 17 años por la Ruta de la Seda hasta India en busca de textos budistas auténticos (629-645). Sus traducciones del sánscrito al chino fundamentaron escuelas budistas chinas. Inspiró la novela Viaje al Oeste.' },
  { id: 'zhao-kuangyin', name: 'Zhao Kuangyin (Song Taizu)', name_en: 'Emperor Taizu of Song', year_born: 927, year_died: 976,
    polity: ['dinastia-song'], region: 'este-asia', role: 'politico', tags: ['emperador', 'fundador-song'],
    sources: ['https://es.wikipedia.org/wiki/Taizu_de_Song'],
    body: 'General que reunificó China tras el periodo de las Cinco Dinastías y fundó la dinastía Song (960). Sus reformas redujeron el poder militar regional a favor de la burocracia civil examinada — modelo Song.' },
  { id: 'su-shi', name: 'Su Shi (Su Dongpo)', name_en: 'Su Shi', year_born: 1037, year_died: 1101,
    polity: ['dinastia-song'], region: 'este-asia', role: 'artista', tags: ['poeta', 'caligrafo', 'literati'],
    sources: ['https://es.wikipedia.org/wiki/Su_Shi'],
    body: 'Polímata literato de la Song del Norte: poesía, caligrafía, pintura, gastronomía, política. Exiliado varias veces por sus críticas a las reformas de Wang Anshi; sus poemas del exilio son obras maestras.' },
  { id: 'zhu-xi', name: 'Zhu Xi', name_en: 'Zhu Xi', year_born: 1130, year_died: 1200,
    polity: ['dinastia-song'], region: 'este-asia', role: 'filosofo', tags: ['neoconfucianismo', 'sintetizador'],
    sources: ['https://es.wikipedia.org/wiki/Zhu_Xi'],
    body: 'Filósofo Song que sintetizó el neoconfucianismo. Sus comentarios sobre los Cuatro Libros fueron la base curricular de los exámenes imperiales chinos desde 1313 hasta 1905, dando forma al pensamiento de Asia oriental por 600 años.' },
  { id: 'zhu-yuanzhang', name: 'Zhu Yuanzhang (Hongwu)', name_en: 'Emperor Hongwu', year_born: 1328, year_died: 1398,
    polity: ['dinastia-ming'], region: 'este-asia', role: 'politico', tags: ['emperador', 'fundador-ming'],
    sources: ['https://es.wikipedia.org/wiki/Hongwu'],
    body: 'Fundador de la dinastía Ming (1368), expulsó a los mongoles Yuan. Originalmente monje budista mendicante, ascendió tras décadas de guerra rebelde. Su reinado autoritario y purgas marcaron la administración Ming.' },
  { id: 'yongle', name: 'Yongle', name_en: 'Yongle Emperor', year_born: 1360, year_died: 1424,
    polity: ['dinastia-ming'], region: 'este-asia', role: 'politico', tags: ['emperador', 'ciudad-prohibida', 'naval'],
    sources: ['https://es.wikipedia.org/wiki/Yongle'],
    body: 'Tercer emperador Ming (1402-1424). Trasladó la capital a Beijing y construyó la Ciudad Prohibida. Patrocinó las expediciones navales de Zheng He y el monumental Enciclopedia Yongle.' },
  { id: 'zheng-he', name: 'Zheng He', name_en: 'Zheng He', year_born: 1371, year_died: 1433,
    polity: ['dinastia-ming'], region: 'este-asia', role: 'militar', tags: ['almirante', 'expediciones-tesoro'],
    sources: ['https://es.wikipedia.org/wiki/Zheng_He'],
    body: 'Eunuco-almirante musulmán al servicio de Yongle. Lideró siete expediciones navales (1405-1433) con flotas de hasta 300 barcos, alcanzando el Sudeste Asiático, India, Arabia y África Oriental — décadas antes que los portugueses.' },
  { id: 'kangxi', name: 'Kangxi', name_en: 'Kangxi Emperor', year_born: 1654, year_died: 1722,
    polity: ['dinastia-qing'], region: 'este-asia', role: 'politico', tags: ['emperador', 'reinado-largo', 'consolidacion-qing'],
    sources: ['https://es.wikipedia.org/wiki/Kangxi'],
    body: 'Cuarto emperador Qing, reinó 61 años (1661-1722) — el reinado más largo de China. Consolidó el control manchú sobre China, conquistó Taiwán, contuvo a los rusos en Asia Central, patrocinó el Diccionario Kangxi.' },
  { id: 'qianlong', name: 'Qianlong', name_en: 'Qianlong Emperor', year_born: 1711, year_died: 1799,
    polity: ['dinastia-qing'], region: 'este-asia', role: 'politico', tags: ['emperador', 'apogeo-qing'],
    sources: ['https://es.wikipedia.org/wiki/Qianlong'],
    body: 'Quinto emperador Qing (1735-1796). Apogeo territorial: campañas en Xinjiang, Tibet, Vietnam, Birmania, Nepal. Abdicó voluntariamente para no superar el reinado de su abuelo Kangxi. Patrocinó la Siku Quanshu, mayor compilación literaria china.' },
  { id: 'cixi', name: 'Cixi (emperatriz viuda)', name_en: 'Empress Dowager Cixi', year_born: 1835, year_died: 1908,
    polity: ['dinastia-qing'], region: 'este-asia', role: 'politico', tags: ['emperatriz', 'declive-qing'],
    sources: ['https://es.wikipedia.org/wiki/Cixí'],
    body: 'Concubina ascendida a regente. Controló el poder Qing durante 47 años (1861-1908) en nombre de emperadores menores. Reprimió la rebelión Boxer (1900); sus reformas tardías no impidieron la caída de la dinastía en 1911.' },
  { id: 'sejong-el-grande', name: 'Sejong el Grande', name_en: 'Sejong the Great', year_born: 1397, year_died: 1450,
    polity: ['joseon'], region: 'este-asia', role: 'politico', tags: ['rey', 'hangul', 'reformador'],
    sources: ['https://es.wikipedia.org/wiki/Sejong_el_Grande'],
    body: 'Cuarto rey de Joseon (1418-1450). Su mayor legado: la invención del alfabeto coreano hangul (1443), diseñado deliberadamente para alfabetizar al pueblo. También promovió astronomía, agricultura, medicina e impresión.' },
  { id: 'yi-sun-sin', name: 'Yi Sun-sin', name_en: 'Yi Sun-sin', year_born: 1545, year_died: 1598,
    polity: ['joseon'], region: 'este-asia', role: 'militar', tags: ['almirante', 'guerras-imjin', 'barco-tortuga'],
    sources: ['https://es.wikipedia.org/wiki/Yi_Sun-sin'],
    body: 'Almirante coreano que defendió Joseon contra las invasiones japonesas de Hideyoshi (1592-1598). Sus innovadores "barcos tortuga" blindados ganaron sucesivas batallas navales contra fuerzas muy superiores. Muerto en combate en Noryang.' },
  { id: 'tokugawa-ieyasu', name: 'Tokugawa Ieyasu', name_en: 'Tokugawa Ieyasu', year_born: 1543, year_died: 1616,
    polity: ['shogunato-tokugawa'], region: 'este-asia', role: 'politico', tags: ['shogun', 'fundador-tokugawa', 'sekigahara'],
    sources: ['https://es.wikipedia.org/wiki/Tokugawa_Ieyasu'],
    body: 'Daimyo que tras la batalla de Sekigahara (1600) unificó Japón bajo su autoridad y fundó el shogunato Tokugawa (1603). Estableció Edo (actual Tokio) como sede del poder real durante 250 años.' },
  { id: 'miyamoto-musashi', name: 'Miyamoto Musashi', name_en: 'Miyamoto Musashi', year_born: 1584, year_died: 1645,
    polity: ['shogunato-tokugawa'], region: 'este-asia', role: 'militar', tags: ['ronin', 'esgrima', 'filosofo-marcial'],
    sources: ['https://es.wikipedia.org/wiki/Miyamoto_Musashi'],
    body: 'Espadachín ronin japonés invicto en más de 60 duelos. Autor del Gorin no Sho (Libro de los Cinco Anillos, 1645), tratado de estrategia que se sigue leyendo en escuelas de negocios y artes marciales.' },
  { id: 'matsuo-basho', name: 'Matsuo Bashō', name_en: 'Matsuo Bashō', year_born: 1644, year_died: 1694,
    polity: ['shogunato-tokugawa'], region: 'este-asia', role: 'artista', tags: ['poeta', 'haiku'],
    sources: ['https://es.wikipedia.org/wiki/Matsuo_Bashō'],
    body: 'Poeta del periodo Edo que elevó el haiku de juego literario a forma artística mayor. Su diario poético Oku no Hosomichi (Sendas de Oku, 1694) es uno de los textos canónicos de la literatura japonesa.' },

  // ─── Sudeste Asiático (6) ───────────────────────────────────────────────
  { id: 'jayavarman-ii', name: 'Jayavarman II', name_en: 'Jayavarman II', year_born: 770, year_died: 850,
    polity: ['imperio-khmer'], region: 'sudeste-asia', role: 'politico', tags: ['rey', 'fundador-khmer', 'devaraja'],
    sources: ['https://es.wikipedia.org/wiki/Jayavarman_II'],
    body: 'Fundador del Imperio Khmer (802 CE), unificó los principados jemeres y proclamó el culto del devaraja (rey-dios). Estableció la capital cerca de Angkor.' },
  { id: 'jayavarman-vii', name: 'Jayavarman VII', name_en: 'Jayavarman VII', year_born: 1122, year_died: 1218,
    polity: ['imperio-khmer'], region: 'sudeste-asia', role: 'politico', tags: ['rey', 'apogeo-khmer', 'budismo-mahayana'],
    sources: ['https://es.wikipedia.org/wiki/Jayavarman_VII'],
    body: 'Rey jemer (1181-1218) en el apogeo del Imperio Khmer. Convirtió la religión estatal del hinduismo al budismo mahayana. Construyó Angkor Thom, el Bayón, hospitales y caminos por todo el imperio.' },
  { id: 'raden-wijaya', name: 'Raden Wijaya', name_en: 'Raden Wijaya', year_born: 1265, year_died: 1309,
    polity: ['imperio-majapahit'], region: 'sudeste-asia', role: 'politico', tags: ['rey', 'fundador-majapahit'],
    sources: ['https://es.wikipedia.org/wiki/Raden_Wijaya'],
    body: 'Fundador del Imperio Majapahit en Java oriental (1293 CE), tras astutamente repeler una invasión mongola usando alianzas y traiciones tácticas. Estableció Trowulan como capital.' },
  { id: 'gajah-mada', name: 'Gajah Mada', name_en: 'Gajah Mada', year_born: 1290, year_died: 1364,
    polity: ['imperio-majapahit'], region: 'sudeste-asia', role: 'politico', tags: ['primer-ministro', 'patih', 'nusantara'],
    sources: ['https://es.wikipedia.org/wiki/Gajah_Mada'],
    body: 'Mahapatih (primer ministro) de Majapahit. Su juramento Sumpah Palapa (1336) prometió no descansar hasta unificar el archipiélago malayo (Nusantara) — anticipo discursivo de la Indonesia moderna.' },
  { id: 'ramathibodi-i', name: 'Ramathibodi I (U Thong)', name_en: 'Ramathibodi I', year_born: 1314, year_died: 1369,
    polity: ['reino-de-ayutthaya'], region: 'sudeste-asia', role: 'politico', tags: ['rey', 'fundador-ayutthaya'],
    sources: ['https://es.wikipedia.org/wiki/Ramathibodi_I'],
    body: 'Fundador del reino de Ayutthaya (1351), eligió la ubicación del delta del Chao Phraya como centro comercial estratégico. Codificó el primer corpus legal thai (la "Ley de las Tres Estampas").' },
  { id: 'naresuan', name: 'Naresuan', name_en: 'Naresuan', year_born: 1555, year_died: 1605,
    polity: ['reino-de-ayutthaya'], region: 'sudeste-asia', role: 'militar', tags: ['rey', 'guerra-birmana'],
    sources: ['https://es.wikipedia.org/wiki/Naresuan'],
    body: 'Rey de Ayutthaya (1590-1605). Liberó al reino del vasallaje birmano tras décadas, derrotando al príncipe heredero birmano en un duelo a lomos de elefante (1593) — escena fundacional del nacionalismo thai.' },

  // ─── Estepa / Asia Central (9) ──────────────────────────────────────────
  { id: 'ateas', name: 'Ateas', name_en: 'Ateas', year_born: -429, year_died: -339,
    polity: ['escitas'], region: 'estepa', role: 'politico', tags: ['rey-escita'],
    sources: ['https://es.wikipedia.org/wiki/Ateas'],
    body: 'Rey escita que unificó las tribus de la estepa póntica en el siglo IV BCE. Mantuvo equilibrios con Filipo II de Macedonia hasta enfrentarse a él en una batalla en la que murió a los 90 años (339 BCE).' },
  { id: 'modu-chanyu', name: 'Modu Chanyu', name_en: 'Modu Chanyu', year_born: -234, year_died: -174,
    polity: ['imperio-xiongnu'], region: 'estepa', role: 'politico', tags: ['chanyu', 'fundador-xiongnu', 'caballeria'],
    sources: ['https://es.wikipedia.org/wiki/Modu_Chanyu'],
    body: 'Fundador del imperio Xiongnu (209 BCE) tras asesinar a su padre. Unificó las tribus de la estepa mongol-mancha, derrotó al recién fundado Han, forzándolo al sistema de heqin (matrimonios y tributo).' },
  { id: 'bumin-qaghan', name: 'Bumin Qaghan', name_en: 'Bumin Qaghan', year_born: 500, year_died: 552,
    polity: ['khaganato-turco'], region: 'estepa', role: 'politico', tags: ['qaghan', 'fundador-khaganato-turco'],
    sources: ['https://es.wikipedia.org/wiki/Bumin_Qaghan'],
    body: 'Fundador del Primer Khaganato Turco (552 CE) tras derrotar a los rouran. Primer gobernante en autoreferenciarse como "turco", base lingüística de toda la familia turcomongola posterior.' },
  { id: 'genghis-khan', name: 'Genghis Khan', name_en: 'Genghis Khan', year_born: 1162, year_died: 1227,
    polity: ['imperio-mongol'], region: 'estepa', role: 'politico', tags: ['fundador-mongol', 'conquistador'],
    wikidata: 'Q720',
    sources: ['https://es.wikipedia.org/wiki/Gengis_Kan'],
    body: 'Temüjin, unificó las tribus mongolas (1206) tomando el título Genghis Khan. En 20 años conquistó el norte de China, Asia Central, el Califato Jorezmita y partes de Persia y el Cáucaso, sentando las bases del mayor imperio terrestre contiguo de la historia.' },
  { id: 'ogedei-khan', name: 'Ögedei Khan', name_en: 'Ögedei Khan', year_born: 1186, year_died: 1241,
    polity: ['imperio-mongol'], region: 'estepa', role: 'politico', tags: ['gran-khan', 'fundador-karakorum'],
    sources: ['https://es.wikipedia.org/wiki/Ogodei_Kan'],
    body: 'Tercer hijo y sucesor de Genghis Khan. Como Gran Khan (1229-1241), completó la conquista del norte de China, invadió Rusia y Polonia/Hungría. Su muerte interrumpió la invasión europea — los ejércitos se retiraron a Karakorum para el kurultai.' },
  { id: 'kublai-khan', name: 'Kublai Khan', name_en: 'Kublai Khan', year_born: 1215, year_died: 1294,
    polity: ['imperio-mongol'], region: 'estepa', role: 'politico', tags: ['gran-khan', 'fundador-yuan'],
    sources: ['https://es.wikipedia.org/wiki/Kublai_Kan'],
    body: 'Nieto de Genghis Khan, fundó la dinastía Yuan en China (1271). Completó la conquista de Song del Sur (1279). Su corte cosmopolita recibió a viajeros como Marco Polo. Fracasó al intentar invadir Japón (1274, 1281) y Java.' },
  { id: 'hulagu-khan', name: 'Hulagu Khan', name_en: 'Hulagu Khan', year_born: 1217, year_died: 1265,
    polity: ['imperio-mongol'], region: 'estepa', role: 'militar', tags: ['ilkanato', 'saqueo-bagdad'],
    sources: ['https://es.wikipedia.org/wiki/Hulagu_Kan'],
    body: 'Nieto de Genghis Khan y fundador del Ilkanato. Saqueó Bagdad en 1258 ejecutando al último califa abasí — fin del califato abasí clásico y trauma cultural del mundo islámico. Detenido en Ayn Jalut (1260) por los mamelucos egipcios.' },
  { id: 'tamerlan', name: 'Tamerlán (Timur)', name_en: 'Timur', year_born: 1336, year_died: 1405,
    polity: ['imperio-timurida'], region: 'estepa', role: 'politico', tags: ['emir', 'fundador-timurida', 'conquistador'],
    sources: ['https://es.wikipedia.org/wiki/Tamerlán'],
    body: 'Turcomongol musulmán que se reivindicó como sucesor de Genghis Khan, fundando el Imperio Timúrida (1370) con capital en Samarcanda. Conquistó Persia, Anatolia, Levante, norte de India; murió camino a invadir China.' },
  { id: 'ulugh-beg', name: 'Ulugh Beg', name_en: 'Ulugh Beg', year_born: 1394, year_died: 1449,
    polity: ['imperio-timurida'], region: 'estepa', role: 'cientifico', tags: ['astronomo', 'matematico', 'samarkanda'],
    sources: ['https://es.wikipedia.org/wiki/Ulugh_Beg'],
    body: 'Nieto de Tamerlán, sultán y astrónomo. Construyó en Samarcanda un observatorio de tamaño excepcional cuyas tablas estelares (Zij-i Sultani, 1437) fueron las más precisas del mundo durante 200 años.' },

  // ─── Américas (12) ──────────────────────────────────────────────────────
  { id: 'yax-kuk-mo', name: "K'inich Yax K'uk' Mo'", name_en: "K'inich Yax K'uk' Mo'", year_born: 380, year_died: 437,
    polity: ['maya-clasico'], region: 'americas', role: 'politico', tags: ['rey-maya', 'fundador-copan'],
    sources: ['https://es.wikipedia.org/wiki/K%27inich_Yax_K%27uk%27_Mo%27'],
    body: 'Fundador del linaje real de Copán (Honduras) en 426 CE. Posiblemente originario de Teotihuacán, su llegada marca la consolidación de Copán como centro maya clásico mayor.' },
  { id: 'pakal-el-grande', name: "K'inich Janaab' Pakal (Pakal el Grande)", name_en: 'K\'inich Janaab\' Pakal', year_born: 603, year_died: 683,
    polity: ['maya-clasico'], region: 'americas', role: 'politico', tags: ['rey-maya', 'palenque'],
    sources: ['https://es.wikipedia.org/wiki/Pakal'],
    body: 'Ajaw (rey) de la ciudad-estado maya de Palenque durante 68 años (615-683). Su tumba en el Templo de las Inscripciones contenía la lápida labrada más famosa del arte maya, descubierta intacta en 1952.' },
  { id: 'itzcoatl', name: 'Itzcóatl', name_en: 'Itzcoatl', year_born: 1380, year_died: 1440,
    polity: ['imperio-azteca'], region: 'americas', role: 'politico', tags: ['huey-tlatoani', 'triple-alianza'],
    sources: ['https://es.wikipedia.org/wiki/Itzcóatl'],
    body: 'Cuarto huey tlatoani de Tenochtitlan (1427-1440). Junto con Nezahualcóyotl de Texcoco y el tlatoani de Tlacopan formó la Triple Alianza (1428) que sentó las bases del Imperio Azteca.' },
  { id: 'moctezuma-i', name: 'Moctezuma I', name_en: 'Moctezuma I', year_born: 1397, year_died: 1469,
    polity: ['imperio-azteca'], region: 'americas', role: 'politico', tags: ['huey-tlatoani', 'expansion-imperial'],
    sources: ['https://es.wikipedia.org/wiki/Moctezuma_I'],
    body: 'Quinto huey tlatoani (1440-1469). Expandió el imperio azteca más allá del Valle de México, llegando hasta la Huasteca y Oaxaca. Reformó el sistema legal y de educación.' },
  { id: 'moctezuma-ii', name: 'Moctezuma II', name_en: 'Moctezuma II', year_born: 1466, year_died: 1520,
    polity: ['imperio-azteca'], region: 'americas', role: 'politico', tags: ['huey-tlatoani', 'conquista-espanola'],
    sources: ['https://es.wikipedia.org/wiki/Moctezuma_II'],
    body: 'Noveno huey tlatoani (1502-1520). Bajo su mandato llegaron Hernán Cortés y los españoles (1519). Capturado en su propio palacio, murió en circunstancias debatidas durante la Noche Triste — antesala de la caída de Tenochtitlan (1521).' },
  { id: 'cuauhtemoc', name: 'Cuauhtémoc', name_en: 'Cuauhtémoc', year_born: 1496, year_died: 1525,
    polity: ['imperio-azteca'], region: 'americas', role: 'politico', tags: ['huey-tlatoani', 'resistencia', 'ultimo-mexica'],
    sources: ['https://es.wikipedia.org/wiki/Cuauhtémoc'],
    body: 'Último huey tlatoani mexica (1520-1521). Lideró la defensa final de Tenochtitlan. Capturado tras la rendición, fue torturado para revelar tesoros y finalmente ejecutado por Cortés. Símbolo del nacionalismo mexicano moderno.' },
  { id: 'nezahualcoyotl', name: 'Nezahualcóyotl', name_en: 'Nezahualcoyotl', year_born: 1402, year_died: 1472,
    polity: [], region: 'americas', role: 'artista', tags: ['rey-poeta', 'texcoco'],
    sources: ['https://es.wikipedia.org/wiki/Nezahualcóyotl'],
    body: 'Rey-poeta de Texcoco (1431-1472), parte de la Triple Alianza azteca aunque su polity (Acolhuacan/Texcoco) no esté como entidad separada en v1. Considerado uno de los grandes poetas en lengua náhuatl precolombina.' },
  { id: 'pachacuti', name: 'Pachacuti', name_en: 'Pachacuti', year_born: 1418, year_died: 1471,
    polity: ['imperio-inca'], region: 'americas', role: 'politico', tags: ['sapa-inca', 'transformador-imperial'],
    sources: ['https://es.wikipedia.org/wiki/Pachacútec'],
    body: 'Noveno sapa inca (1438-1471), transformó el pequeño reino del Cuzco en el Tawantinsuyu — el imperio andino. Reorganizó el sistema de mit\'a, redistribución territorial, y planificó/construyó Machu Picchu.' },
  { id: 'tupac-yupanqui', name: 'Túpac Inca Yupanqui', name_en: 'Túpac Inca Yupanqui', year_born: 1441, year_died: 1493,
    polity: ['imperio-inca'], region: 'americas', role: 'politico', tags: ['sapa-inca', 'expansion-territorial'],
    sources: ['https://es.wikipedia.org/wiki/Túpac_Inca_Yupanqui'],
    body: 'Décimo sapa inca (1471-1493), hijo de Pachacuti. Extendió el imperio hasta el actual norte de Argentina/Chile en el sur y Ecuador en el norte. Posiblemente realizó una expedición naval al Pacífico — debatido.' },
  { id: 'huayna-capac', name: 'Huayna Cápac', name_en: 'Huayna Capac', year_born: 1467, year_died: 1527,
    polity: ['imperio-inca'], region: 'americas', role: 'politico', tags: ['sapa-inca', 'maxima-extension'],
    sources: ['https://es.wikipedia.org/wiki/Huayna_Cápac'],
    body: 'Undécimo sapa inca (1493-1527), apogeo territorial del Tawantinsuyu. Murió súbitamente — probablemente por viruela traída por contacto indirecto con europeos en Centroamérica, años antes de la llegada física de Pizarro. Su muerte desató la guerra civil entre Huáscar y Atahualpa.' },
  { id: 'atahualpa', name: 'Atahualpa', name_en: 'Atahualpa', year_born: 1502, year_died: 1533,
    polity: ['imperio-inca'], region: 'americas', role: 'politico', tags: ['sapa-inca', 'conquista-espanola'],
    sources: ['https://es.wikipedia.org/wiki/Atahualpa'],
    body: 'Decimotercer y último sapa inca soberano. Venció a su medio hermano Huáscar en la guerra civil incaica y fue capturado por Pizarro en Cajamarca (1532). Pagó el rescate más grande de la historia y aun así fue ejecutado.' },
  { id: 'tupac-amaru-i', name: 'Túpac Amaru I', name_en: 'Túpac Amaru I', year_born: 1545, year_died: 1572,
    polity: ['imperio-inca'], region: 'americas', role: 'politico', tags: ['ultimo-sapa-inca', 'vilcabamba'],
    sources: ['https://es.wikipedia.org/wiki/Túpac_Amaru_I'],
    body: 'Último sapa inca de la resistencia en Vilcabamba (1571-1572). Capturado y ejecutado en el Cuzco bajo el virrey Toledo, su decapitación marca el fin formal del estado incaico independiente.' },
];
