// 50 polities curadas para v1 con balance no-Eurocentric.
// Distribución (cumple cuotas mínimas PLAN §F3/paso-3):
//   Mediterráneo:        4  (cuota ≥4)
//   Europa post-Roma:    5  (cuota ≥4)
//   Medio Oriente:       6  (cuota ≥5)
//   Norte de África:     3  (cuota ≥3)
//   África Sub-Sah:      6  (cuota ≥5)
//   Sur de Asia:         5  (cuota ≥5)
//   Este de Asia:        7  (cuota ≥5)
//   Sudeste Asiático:    3  (cuota ≥3)
//   Estepa / Asia C.:    5  (cuota ≥5)
//   Américas:            6  (cuota ≥5)
//                       ───
//                       50
//
// Curación documentada (con reasoning por entrada) en docs/polities-curation.md.
// religion_dominant queda vacío en F3 — F4 lo populará al ingestar religions.
// predecessors/successors quedan vacíos para evitar refs colgantes a polities no en v1.
// wikidata se incluye sólo donde la confianza es alta; revisión pendiente.

export const POLITIES_SEED = [
  // ─── Mediterráneo (4) ─────────────────────────────────────────────────────
  {
    id: 'cartago',
    name: 'Cartago',
    name_en: 'Carthage',
    region: 'mediterraneo',
    start_year: -814,
    end_year: -146,
    capital: 'Cartago',
    tags: ['imperio', 'fenicia', 'naval', 'comercio'],
    wikidata: 'Q6343',
    sources: ['https://es.wikipedia.org/wiki/Cartago'],
    body: 'Civilización púnica fundada por colonos fenicios de Tiro en la costa norteafricana (actual Túnez). Construyó un imperio comercial y naval que dominó el Mediterráneo occidental durante siglos, controlando Sicilia, Cerdeña, Iberia y rutas atlánticas. Su rivalidad con Roma desembocó en las tres Guerras Púnicas (264-146 BCE), y su destrucción final marca el fin del orden mediterráneo púnico.',
  },
  {
    id: 'macedonia-helenistica',
    name: 'Imperio Macedonio (Helenístico)',
    name_en: 'Macedonian / Hellenistic Empires',
    region: 'mediterraneo',
    start_year: -336,
    end_year: -30,
    capital: 'Pella → Alejandría / Antioquía / Pérgamo',
    tags: ['imperio', 'helenismo', 'conquista'],
    wikidata: 'Q645883',
    sources: ['https://es.wikipedia.org/wiki/Imperio_macedónico'],
    body: 'Iniciado con la conquista persa por Alejandro Magno (336-323 BCE), el periodo helenístico se extiende a través de los reinos diadocos: Seléucida (Asia), Ptolemaico (Egipto), Antigónida (Macedonia), Pérgamo. La cultura griega se difunde desde el Mediterráneo hasta el Indo. Termina con la conquista romana de Egipto en 30 BCE (Cleopatra VII).',
  },
  {
    id: 'imperio-bizantino',
    name: 'Imperio Bizantino',
    name_en: 'Byzantine Empire',
    region: 'mediterraneo',
    start_year: 330,
    end_year: 1453,
    capital: 'Constantinopla',
    tags: ['imperio', 'cristianismo', 'ortodoxia', 'continuidad-romana'],
    wikidata: 'Q42968',
    sources: ['https://es.wikipedia.org/wiki/Imperio_bizantino'],
    body: 'Continuidad institucional del Imperio Romano de Oriente desde la refundación de Constantinopla por Constantino I (330 CE). Sobrevive a la caída del Occidente (476) por casi un milenio, preservando el derecho romano, el griego clásico y el cristianismo ortodoxo. Cae ante la conquista otomana de Constantinopla en 1453, fecha tradicionalmente usada para marcar el fin de la Edad Media.',
  },

  // ─── Europa post-Roma (5) ─────────────────────────────────────────────────
  {
    id: 'sacro-imperio-romano-germanico',
    name: 'Sacro Imperio Romano Germánico',
    name_en: 'Holy Roman Empire',
    region: 'europa',
    start_year: 962,
    end_year: 1806,
    capital: 'Aquisgrán / Praga / Viena',
    tags: ['imperio', 'cristianismo', 'feudalismo', 'electoral'],
    wikidata: 'Q12548',
    sources: ['https://es.wikipedia.org/wiki/Sacro_Imperio_Romano_Germánico'],
    body: 'Polity multiétnica centrada en territorios germánicos, fundada con la coronación imperial de Otón I por el papa (962 CE) reivindicando continuidad romana cristiana. Estructura confederal de electores y príncipes-obispos, con un emperador elegido. Disuelto por Napoleón en 1806; su disolución marca el inicio de la "Cuestión Alemana" del siglo XIX.',
  },
  {
    id: 'reino-de-inglaterra',
    name: 'Reino de Inglaterra / Reino Unido',
    name_en: 'Kingdom of England / United Kingdom',
    region: 'europa',
    start_year: 927,
    end_year: 2026,
    capital: 'Londres',
    tags: ['monarquia', 'imperio', 'naval', 'protestantismo'],
    wikidata: 'Q179876',
    sources: ['https://es.wikipedia.org/wiki/Historia_del_Reino_Unido'],
    body: 'Unificación de los reinos anglosajones bajo Athelstan (927 CE) → conquista normanda (1066) → Magna Carta (1215) → reformación anglicana (1534) → Acta de Unión con Escocia (1707) → imperio global (1815-1945) → disolución del imperio (post-WW2). Continuidad institucional como monarquía constitucional hasta el presente.',
  },
  {
    id: 'reino-de-francia',
    name: 'Reino de Francia',
    name_en: 'Kingdom of France',
    region: 'europa',
    start_year: 843,
    end_year: 1792,
    capital: 'París',
    tags: ['monarquia', 'cristianismo', 'catolicismo', 'feudalismo'],
    wikidata: 'Q70972',
    sources: ['https://es.wikipedia.org/wiki/Reino_de_Francia'],
    body: 'Fundado con el Tratado de Verdún (843 CE) que dividió el Imperio Carolingio: Francia Occidentalis bajo Carlos el Calvo. Pasa de monarquía feudal débil (capetos) a estado centralizado (Luis XIV, absolutismo). Termina con la Revolución Francesa (1792) y la proclamación de la Primera República. Sucesores Napoleónicos y republicanos cubren el resto.',
  },
  {
    id: 'imperio-espanol',
    name: 'Imperio Español',
    name_en: 'Spanish Empire',
    region: 'europa',
    start_year: 1492,
    end_year: 1898,
    capital: 'Madrid',
    tags: ['imperio', 'colonialismo', 'catolicismo', 'transatlantico'],
    wikidata: 'Q42585',
    sources: ['https://es.wikipedia.org/wiki/Imperio_español'],
    body: 'Iniciado con la unificación de Castilla y Aragón (1469-1492) y la llegada de Colón a América (1492). Primer imperio global moderno: dominios en América (Nueva España, Perú), Asia (Filipinas), África (Sahara, Guinea, Ceuta, Marruecos), Europa (Países Bajos, Italia, Flandes, Nápoles). Pierde la mayor parte de las colonias americanas con las independencias de 1810-1825; termina con la guerra hispano-estadounidense de 1898.',
  },
  {
    id: 'imperio-ruso',
    name: 'Imperio Ruso',
    name_en: 'Russian Empire',
    region: 'europa',
    start_year: 1283,
    end_year: 1917,
    capital: 'Moscú → San Petersburgo (1712) → Moscú (1918)',
    tags: ['imperio', 'ortodoxia', 'expansion-territorial', 'autocracia'],
    wikidata: 'Q34266',
    sources: ['https://es.wikipedia.org/wiki/Imperio_ruso'],
    body: 'Continuidad desde el Principado de Moscú (1283), elevado a Zarato por Iván IV (1547) y a Imperio por Pedro el Grande (1721). Expansión territorial sostenida: Siberia, Cáucaso, Asia Central, parte de Polonia, Finlandia, Alaska (vendida 1867). Estado autocrático centrado en la ortodoxia rusa. Disuelto por la Revolución de Febrero de 1917; sucedido por la URSS.',
  },

  // ─── Medio Oriente (6) ────────────────────────────────────────────────────
  {
    id: 'sumeria',
    name: 'Sumeria',
    name_en: 'Sumer',
    region: 'medio-oriente',
    start_year: -4500,
    end_year: -1900,
    capital: 'Ur / Uruk / Lagash / Eridu',
    tags: ['ciudad-estado', 'escritura', 'cuneiforme', 'bronce'],
    wikidata: 'Q35525',
    sources: ['https://es.wikipedia.org/wiki/Sumeria'],
    body: 'Civilización fundacional de Mesopotamia (sur del actual Iraq), donde se documenta la primera escritura conocida (cuneiforme, ~3200 BCE). Sistema de ciudades-estado independientes (Ur, Uruk, Lagash, Eridu, Nippur) con periodos de hegemonía rotativa. Innovaciones: rueda, irrigación canalizada, derecho codificado, contabilidad. Asimilada por la cultura acadia tras 2300 BCE.',
  },
  {
    id: 'babilonia',
    name: 'Imperio Babilónico',
    name_en: 'Babylonian Empire',
    region: 'medio-oriente',
    start_year: -1894,
    end_year: -539,
    capital: 'Babilonia',
    tags: ['imperio', 'codigo-hammurabi', 'astronomia', 'mesopotamia'],
    wikidata: 'Q5684',
    sources: ['https://es.wikipedia.org/wiki/Babilonia'],
    body: 'Polity dominante en Mesopotamia con dos fases: Imperio Paleo-Babilónico (1894-1595 BCE, dinastía amorita, Código de Hammurabi ~1754 BCE) y Imperio Neo-Babilónico (626-539 BCE, dinastía caldea, Nabucodonosor II, conquista de Judá 587 BCE). Caen ante Ciro el Grande de Persia (539 BCE). Legado: astronomía, álgebra, sistema sexagesimal.',
  },
  {
    id: 'imperio-persa-aquemenida',
    name: 'Imperio Persa Aqueménida',
    name_en: 'Achaemenid Empire',
    region: 'medio-oriente',
    start_year: -550,
    end_year: -330,
    capital: 'Persépolis / Susa / Pasargadae',
    tags: ['imperio', 'zoroastrismo', 'pluralismo', 'satrapias'],
    wikidata: 'Q24832',
    sources: ['https://es.wikipedia.org/wiki/Imperio_aqueménida'],
    body: 'Primer imperio realmente global de la antigüedad, fundado por Ciro el Grande (550 BCE). Extensión desde el Indo hasta el Egeo y Egipto, con sistema de satrapías, correo postal real, tolerancia religiosa (libertad a los judíos en Babilonia, 539 BCE), zoroastrismo dominante. Cae ante la conquista de Alejandro Magno (330 BCE). Modelo administrativo influye en todos los imperios persas posteriores.',
  },
  {
    id: 'imperio-sasanida',
    name: 'Imperio Sasánida',
    name_en: 'Sasanian Empire',
    region: 'medio-oriente',
    start_year: 224,
    end_year: 651,
    capital: 'Ctesifonte',
    tags: ['imperio', 'zoroastrismo', 'persa', 'antiroma'],
    wikidata: 'Q83476',
    sources: ['https://es.wikipedia.org/wiki/Imperio_sasánida'],
    body: 'Última gran dinastía persa pre-islámica, fundada por Ardacher I (224 CE) tras derrotar a los partos. Restablece el zoroastrismo como religión estatal y reivindica continuidad aqueménida. Rival principal del Imperio Romano/Bizantino durante 4 siglos. Su agotamiento militar tras las guerras con Bizancio facilita la conquista árabe-islámica (633-651), última batalla en Nahavand.',
  },
  {
    id: 'califato-abasi',
    name: 'Califato Abasí',
    name_en: 'Abbasid Caliphate',
    region: 'medio-oriente',
    start_year: 750,
    end_year: 1258,
    capital: 'Bagdad',
    tags: ['califato', 'islam', 'edad-de-oro', 'casa-de-sabiduria'],
    wikidata: 'Q11704',
    sources: ['https://es.wikipedia.org/wiki/Califato_abasí'],
    body: 'Califato dominante del mundo islámico tras derrocar a los Omeyas (750 CE), funda Bagdad como capital y centro intelectual ("Casa de la Sabiduría"). Edad de oro del islam: traducciones del griego, álgebra, óptica, medicina (al-Razi, Avicena), filosofía (al-Farabi, al-Kindi). Pierde poder real frente a sultanatos turcos (selyúcidas, mamelucos); cae con el saqueo mongol de Bagdad (1258).',
  },
  {
    id: 'imperio-otomano',
    name: 'Imperio Otomano',
    name_en: 'Ottoman Empire',
    region: 'medio-oriente',
    start_year: 1299,
    end_year: 1922,
    capital: 'Bursa → Edirne → Constantinopla (1453)',
    tags: ['imperio', 'islam', 'sunni', 'multietnico'],
    wikidata: 'Q12560',
    sources: ['https://es.wikipedia.org/wiki/Imperio_otomano'],
    body: 'Fundado por Osman I (1299 CE) en Anatolia. Conquista Constantinopla (1453) bajo Mehmed II terminando con Bizancio. Apogeo bajo Solimán el Magnífico (1520-1566): Balcanes, Anatolia, Mesopotamia, Levante, Egipto, Hejaz, Magreb. Estado multiétnico con sistema millet (autonomía religiosa de cristianos y judíos). Disuelto tras la WWI; sucedido por la República de Turquía (1923).',
  },

  // ─── Norte de África (3) ──────────────────────────────────────────────────
  {
    id: 'egipto-faraonico',
    name: 'Egipto Faraónico',
    name_en: 'Ancient Egypt',
    region: 'norte-africa',
    start_year: -3100,
    end_year: -332,
    capital: 'Menfis / Tebas / Amarna',
    tags: ['imperio', 'piramides', 'faraones', 'nilo'],
    wikidata: 'Q11768',
    sources: ['https://es.wikipedia.org/wiki/Antiguo_Egipto'],
    body: 'Civilización del valle del Nilo, unificación inicial atribuida a Narmer (~3100 BCE). Estructura clásica de 30 dinastías agrupadas en Reino Antiguo (pirámides de Giza), Medio (Tebas) y Nuevo (imperio: Ramsés II, Akenatón). Religión politeísta centrada en Ra y Osiris. Conquistada por Alejandro Magno (332 BCE), iniciando el periodo ptolemaico que termina con la conquista romana (30 BCE).',
  },
  {
    id: 'reino-de-kush',
    name: 'Reino de Kush',
    name_en: 'Kingdom of Kush',
    region: 'norte-africa',
    start_year: -1070,
    end_year: 350,
    capital: 'Napata → Meroe',
    tags: ['nubia', 'reino', 'piramides', 'faraones-negros'],
    wikidata: 'Q179232',
    sources: ['https://es.wikipedia.org/wiki/Reino_de_Kush'],
    body: 'Civilización nubia centrada en el actual Sudán, formalizada hacia 1070 BCE. Llegó a conquistar Egipto fundando la dinastía XXV ("faraones negros", 744-656 BCE). Tras su retirada a Nubia, capital se traslada a Meroe (~270 BCE), desarrollando metalurgia del hierro, escritura propia y pirámides distintivas. Cae ante el reino de Aksum (~350 CE).',
  },
  {
    id: 'califato-fatimi',
    name: 'Califato Fatimí',
    name_en: 'Fatimid Caliphate',
    region: 'norte-africa',
    start_year: 909,
    end_year: 1171,
    capital: 'Mahdia → El Cairo (969)',
    tags: ['califato', 'islam', 'chiita', 'ismaili'],
    wikidata: 'Q170027',
    sources: ['https://es.wikipedia.org/wiki/Califato_fatimí'],
    body: 'Califato ismailí chiita fundado por Abdullah al-Mahdi (909 CE) en Ifriqiya (actual Túnez). Conquista Egipto (969) y funda El Cairo como nueva capital. Establece la universidad de al-Azhar. Rivalidad ideológica con el califato Abasí sunita de Bagdad y el omeya de Córdoba. Decae por presiones cruzadas (Cruzadas y Selyúcidas), termina con el ascenso de Saladino (1171).',
  },

  // ─── África Sub-Sahariana (6) ─────────────────────────────────────────────
  {
    id: 'imperio-aksum',
    name: 'Imperio de Aksum',
    name_en: 'Aksumite Empire',
    region: 'africa-subsahariana',
    start_year: 100,
    end_year: 940,
    capital: 'Aksum',
    tags: ['imperio', 'cristianismo', 'comercio', 'estelas'],
    wikidata: 'Q189834',
    sources: ['https://es.wikipedia.org/wiki/Reino_de_Aksum'],
    body: 'Imperio cristiano del Cuerno de África (actual Etiopía-Eritrea), uno de los cuatro grandes poderes mundiales del siglo III según Mani (junto con Roma, Persia y China). Adoptó el cristianismo bajo Ezana (~340 CE) — segundo estado cristiano oficial tras Armenia. Acuñó moneda propia, controló el comercio del Mar Rojo, conquistó Yemen. Decadencia por desplazamiento de rutas comerciales tras la expansión islámica.',
  },
  {
    id: 'imperio-mali',
    name: 'Imperio de Malí',
    name_en: 'Mali Empire',
    region: 'africa-subsahariana',
    start_year: 1235,
    end_year: 1670,
    capital: 'Niani → Tombuctú',
    tags: ['imperio', 'islam', 'oro', 'sahel'],
    wikidata: 'Q83000',
    sources: ['https://es.wikipedia.org/wiki/Imperio_de_Malí'],
    body: 'Imperio del Sahel fundado por Sundiata Keita (1235 CE) tras la batalla de Kirina. Centro comercial transahariano del oro: Mansa Musa (1312-1337), referido como el hombre más rico de la historia, hace su famosa peregrinación a La Meca (1324) llevando tanto oro que devalúa la moneda en El Cairo. Tombuctú emerge como centro intelectual islámico. Decadencia por presiones internas y rebeliones (Songhai, mossi).',
  },
  {
    id: 'imperio-songhai',
    name: 'Imperio Songhai',
    name_en: 'Songhai Empire',
    region: 'africa-subsahariana',
    start_year: 1464,
    end_year: 1591,
    capital: 'Gao',
    tags: ['imperio', 'islam', 'sahel', 'comercio'],
    wikidata: 'Q189444',
    sources: ['https://es.wikipedia.org/wiki/Imperio_Songhai'],
    body: 'Sucesor regional de Malí, consolidado por Sonni Ali (1464-1492) y reorganizado bajo Askia Mohammad I como imperio islámico. Mayor extensión territorial en el África occidental pre-colonial, controla el comercio del oro, sal y esclavos. Tombuctú alcanza su apogeo intelectual con la universidad de Sankoré. Cae en 1591 ante una expedición marroquí armada con arcabuces (batalla de Tondibi).',
  },
  {
    id: 'great-zimbabwe',
    name: 'Reino de Zimbabwe (Great Zimbabwe)',
    name_en: 'Kingdom of Zimbabwe',
    region: 'africa-subsahariana',
    start_year: 1100,
    end_year: 1450,
    capital: 'Great Zimbabwe',
    tags: ['reino', 'shona', 'oro', 'piedra-seca'],
    wikidata: 'Q176197',
    sources: ['https://es.wikipedia.org/wiki/Gran_Zimbabue'],
    body: 'Civilización shona del altiplano africano oriental (actual Zimbabue), célebre por sus construcciones monumentales de piedra seca sin mortero — las ruinas de Great Zimbabwe son las más extensas al sur del Sahara. Economía basada en oro, ganado y comercio del océano Índico (cerámica china recuperada en sitios shonas). Abandonada por razones aún debatidas (sobrepoblación, agotamiento de pastos, cambio de rutas comerciales).',
  },
  {
    id: 'reino-del-kongo',
    name: 'Reino del Kongo',
    name_en: 'Kingdom of Kongo',
    region: 'africa-subsahariana',
    start_year: 1390,
    end_year: 1914,
    capital: 'Mbanza Kongo (São Salvador)',
    tags: ['reino', 'cristianismo', 'bantu', 'comercio'],
    wikidata: 'Q193133',
    sources: ['https://es.wikipedia.org/wiki/Reino_del_Kongo'],
    body: 'Reino centralizado en el África central (frontera moderna Angola/RDC). Adoptó el cristianismo voluntariamente tras contacto con portugueses (1491), bajo el rey Nzinga a Nkuwu / João I. El rey Afonso I (1506-1543) intentó negociar la integración del reino al sistema europeo y limitar la trata transatlántica de esclavos. Decadencia paulatina por presión portuguesa y trata; absorbido formalmente por la colonia portuguesa en 1914.',
  },
  {
    id: 'reino-de-benin',
    name: 'Reino de Benín',
    name_en: 'Benin Empire',
    region: 'africa-subsahariana',
    start_year: 1180,
    end_year: 1897,
    capital: 'Ciudad de Benín',
    tags: ['reino', 'edo', 'bronce', 'comercio'],
    wikidata: 'Q83435',
    sources: ['https://es.wikipedia.org/wiki/Imperio_de_Benín'],
    body: 'Polity del pueblo edo en el actual sur de Nigeria, célebre por las placas de bronce de Benín, una de las tradiciones de fundición artística más sofisticadas de África. Centralización política con monarquía sagrada (Oba). Comercio costero (pimienta, esclavos, marfil) con portugueses, holandeses, británicos. Saqueado y anexado por la "Punitive Expedition" británica de 1897; muchos bronces aún están en colecciones europeas.',
  },

  // ─── Sur de Asia (5) ──────────────────────────────────────────────────────
  {
    id: 'civilizacion-valle-indo',
    name: 'Civilización del Valle del Indo',
    name_en: 'Indus Valley Civilization',
    region: 'sur-asia',
    start_year: -3300,
    end_year: -1300,
    capital: 'Mohenjo-Daro / Harappa',
    tags: ['civilizacion', 'urbana', 'escritura-no-descifrada'],
    wikidata: 'Q11761',
    sources: ['https://es.wikipedia.org/wiki/Cultura_del_valle_del_Indo'],
    body: 'Civilización urbana del valle del Indo (actuales Pakistán e India NW), contemporánea de Sumeria y Egipto. Ciudades planificadas con cuadrículas, sistemas de saneamiento, baños públicos, sellos de esteatita. Escritura aún no descifrada. Declive en ~1900 BCE por causas debatidas (cambios climáticos del río Sarasvati, migraciones indoarias, agotamiento agrícola).',
  },
  {
    id: 'imperio-maurya',
    name: 'Imperio Maurya',
    name_en: 'Maurya Empire',
    region: 'sur-asia',
    start_year: -322,
    end_year: -184,
    capital: 'Pataliputra',
    tags: ['imperio', 'budismo', 'ashoka', 'arthashastra'],
    wikidata: 'Q11760',
    sources: ['https://es.wikipedia.org/wiki/Imperio_Maurya'],
    body: 'Primer imperio que unifica casi todo el subcontinente indio, fundado por Chandragupta Maurya (322 BCE) con la guía estratégica de Chanakya (autor del Arthashastra). Su nieto Ashoka el Grande (268-232 BCE) abandona la guerra tras la batalla de Kalinga y promueve el budismo a escala continental, enviando misiones a Sri Lanka, Asia Central y posiblemente Egipto y Grecia. Decadencia post-Ashoka por fragmentación regional.',
  },
  {
    id: 'imperio-gupta',
    name: 'Imperio Gupta',
    name_en: 'Gupta Empire',
    region: 'sur-asia',
    start_year: 320,
    end_year: 550,
    capital: 'Pataliputra',
    tags: ['imperio', 'hinduismo', 'edad-de-oro', 'matematicas'],
    wikidata: 'Q83055',
    sources: ['https://es.wikipedia.org/wiki/Imperio_Gupta'],
    body: 'Segunda gran unificación del subcontinente indio, fundado por Chandragupta I (320 CE). Edad de oro india clásica: invención del cero como número (Aryabhata, Brahmagupta), sistema decimal posicional, sánscrito clásico, Kalidasa, templos hindúes monumentales, sutras matemáticos y astronómicos. Cae ante incursiones de los Hunos Heftalitas (~550 CE).',
  },
  {
    id: 'imperio-chola',
    name: 'Imperio Chola',
    name_en: 'Chola Empire',
    region: 'sur-asia',
    start_year: 848,
    end_year: 1279,
    capital: 'Thanjavur',
    tags: ['imperio', 'hinduismo', 'tamil', 'naval'],
    wikidata: 'Q1064547',
    sources: ['https://es.wikipedia.org/wiki/Dinastía_Chola'],
    body: 'Imperio del sur de India, predominantemente tamil, con la mayor proyección naval del Sur de Asia pre-moderno. Bajo Rajaraja I y Rajendra I (985-1044 CE) conquista Sri Lanka, Maldivas y realiza expediciones contra Srivijaya (Indonesia). Arquitectura monumental de templos (Brihadeeswara). Disolución por presión del Sultanato de Delhi.',
  },
  {
    id: 'imperio-mogol',
    name: 'Imperio Mogol',
    name_en: 'Mughal Empire',
    region: 'sur-asia',
    start_year: 1526,
    end_year: 1857,
    capital: 'Agra → Delhi',
    tags: ['imperio', 'islam', 'persa-india', 'taj-mahal'],
    wikidata: 'Q33296',
    sources: ['https://es.wikipedia.org/wiki/Imperio_mogol'],
    body: 'Imperio musulmán de origen timúrida fundado por Babur tras la batalla de Panipat (1526 CE). Apogeo bajo Akbar el Grande (1556-1605): política religiosa sincrética, integración hindú-musulmana, administración eficiente. Sucesores célebres: Shah Jahan (Taj Mahal), Aurangzeb (mayor extensión, pero retorno al ortodoxismo islámico). Decadencia paulatina por presiones marathas, sij y europeas; termina con la rebelión india de 1857 (East India Company → Raj británico).',
  },

  // ─── Este de Asia (7) ─────────────────────────────────────────────────────
  {
    id: 'dinastia-han',
    name: 'Dinastía Han',
    name_en: 'Han Dynasty',
    region: 'este-asia',
    start_year: -202,
    end_year: 220,
    capital: "Chang'an / Luoyang",
    tags: ['dinastia', 'china', 'confucianismo', 'ruta-seda'],
    wikidata: 'Q9683',
    sources: ['https://es.wikipedia.org/wiki/Dinastía_Han'],
    body: 'Dinastía imperial china fundada por Liu Bang (202 BCE) tras la caída de los Qin. Consolida el confucianismo como ideología estatal (Wu Di), establece exámenes imperiales, abre la Ruta de la Seda, expande hacia el Asia Central, Vietnam y Corea. "Han" se vuelve sinónimo de identidad china (han ren = el pueblo Han). Dividida en Han Occidental (202 BCE - 9 CE), interludio Xin (9-23 CE), Han Oriental (25-220 CE).',
  },
  {
    id: 'dinastia-tang',
    name: 'Dinastía Tang',
    name_en: 'Tang Dynasty',
    region: 'este-asia',
    start_year: 618,
    end_year: 907,
    capital: "Chang'an",
    tags: ['dinastia', 'china', 'budismo', 'edad-de-oro', 'cosmopolita'],
    wikidata: 'Q9888',
    sources: ['https://es.wikipedia.org/wiki/Dinastía_Tang'],
    body: 'Edad de oro de la China imperial, fundada tras el periodo de los Sui (618 CE). Capital Chang\'an llega a 1M de habitantes (la mayor ciudad del mundo). Cosmopolitismo: budismo florece (peregrinación de Xuanzang), comunidades extranjeras en Chang\'an, intercambios con el Califato Abasí (batalla de Talas, 751 CE) y Bizancio. Poesía clásica china (Li Bai, Du Fu). Cae por la rebelión de An Lushan (755 CE) y fragmentación de las "Cinco Dinastías y Diez Reinos".',
  },
  {
    id: 'dinastia-song',
    name: 'Dinastía Song',
    name_en: 'Song Dynasty',
    region: 'este-asia',
    start_year: 960,
    end_year: 1279,
    capital: 'Kaifeng → Lin\'an (Hangzhou)',
    tags: ['dinastia', 'china', 'tecnologia', 'neoconfucianismo', 'papel-moneda'],
    wikidata: 'Q9912',
    sources: ['https://es.wikipedia.org/wiki/Dinastía_Song'],
    body: 'Revolución tecnológica y económica de la China imperial: pólvora aplicada militarmente, brújula magnética náutica, papel moneda jiaozi, imprenta de tipos móviles (Bi Sheng, ~1040 CE — 4 siglos antes que Gutenberg). Neoconfucianismo (Zhu Xi). Pierde el norte ante los Jurchen (1127 → "Song del Sur"), cae ante los mongoles de Kublai Khan (1279).',
  },
  {
    id: 'dinastia-ming',
    name: 'Dinastía Ming',
    name_en: 'Ming Dynasty',
    region: 'este-asia',
    start_year: 1368,
    end_year: 1644,
    capital: 'Nanjing → Beijing (1421)',
    tags: ['dinastia', 'china', 'gran-muralla', 'naval', 'porcelana'],
    wikidata: 'Q9903',
    sources: ['https://es.wikipedia.org/wiki/Dinastía_Ming'],
    body: 'Restauración Han tras el dominio mongol Yuan, fundada por Zhu Yuanzhang (1368). Reconstrucción de la Gran Muralla en su forma actual. Expediciones navales monumentales de Zheng He (1405-1433) hasta África Oriental. Aislacionismo posterior (haijin). Construcción de la Ciudad Prohibida en Beijing. Decadencia por hambrunas, plagas y rebeliones campesinas; conquistada por los manchúes que fundan Qing (1644).',
  },
  {
    id: 'dinastia-qing',
    name: 'Dinastía Qing',
    name_en: 'Qing Dynasty',
    region: 'este-asia',
    start_year: 1644,
    end_year: 1912,
    capital: 'Beijing',
    tags: ['dinastia', 'china', 'manchu', 'modernizacion-tardia'],
    wikidata: 'Q12557',
    sources: ['https://es.wikipedia.org/wiki/Dinastía_Qing'],
    body: 'Última dinastía imperial china, fundada por los manchúes tras la caída de los Ming (1644). Apogeo territorial bajo Kangxi, Yongzheng y Qianlong (siglo XVIII): control de Mongolia, Tibet, Xinjiang. Siglo XIX: Guerras del Opio (1839-1860), rebelión Taiping (1850-1864, ~30M muertos), humillaciones por potencias occidentales. Caída tras la Revolución Xinhai (1911); abdicación del último emperador Puyi en 1912.',
  },
  {
    id: 'joseon',
    name: 'Joseon',
    name_en: 'Joseon Dynasty',
    region: 'este-asia',
    start_year: 1392,
    end_year: 1897,
    capital: 'Hanyang (Seúl)',
    tags: ['dinastia', 'corea', 'neoconfucianismo', 'hangul'],
    wikidata: 'Q28171',
    sources: ['https://es.wikipedia.org/wiki/Dinastía_Joseon'],
    body: 'Dinastía coreana fundada por Yi Seonggye (1392 CE), 5 siglos de continuidad — una de las dinastías más longevas de la historia. Adopta el neoconfucianismo como ideología estatal. El rey Sejong el Grande inventa el alfabeto hangul (1443), uno de los pocos sistemas de escritura conscientemente diseñados. Resiste invasiones japonesas (1592-1598) y manchúes. Se proclama Imperio Coreano en 1897; anexado por Japón en 1910.',
  },
  {
    id: 'shogunato-tokugawa',
    name: 'Shogunato Tokugawa',
    name_en: 'Tokugawa Shogunate',
    region: 'este-asia',
    start_year: 1603,
    end_year: 1868,
    capital: 'Edo (Tokio)',
    tags: ['shogunato', 'japon', 'sakoku', 'samurai', 'feudal'],
    wikidata: 'Q210826',
    sources: ['https://es.wikipedia.org/wiki/Shogunato_Tokugawa'],
    body: 'Régimen militar del Japón post-unificación, fundado por Tokugawa Ieyasu tras la batalla de Sekigahara (1600). Política de aislamiento (sakoku) desde 1639 — restricciones extremas al comercio exterior, sólo holandeses y chinos en Nagasaki. Sociedad estamental rígida (samurái-campesino-artesano-mercader). Crecimiento urbano y cultura mercantil (ukiyo-e). Termina con la "Restauración Meiji" tras la apertura forzada por Perry (1853-1868).',
  },

  // ─── Sudeste Asiático (3) ─────────────────────────────────────────────────
  {
    id: 'imperio-khmer',
    name: 'Imperio Khmer',
    name_en: 'Khmer Empire',
    region: 'sudeste-asia',
    start_year: 802,
    end_year: 1431,
    capital: 'Angkor',
    tags: ['imperio', 'hinduismo', 'budismo', 'angkor-wat'],
    wikidata: 'Q186098',
    sources: ['https://es.wikipedia.org/wiki/Imperio_jemer'],
    body: 'Imperio jemer fundado por Jayavarman II (802 CE) en el actual Camboya. Centro religioso y administrativo: Angkor — la ciudad pre-industrial más extensa del mundo (~1M habitantes). Templos monumentales hindú-budistas (Angkor Wat, Angkor Thom, Bayon). Sistema sofisticado de canales y baray (reservas hidráulicas). Decadencia por presión thai-ayutthaya y cambios climáticos; saqueo final en 1431.',
  },
  {
    id: 'imperio-majapahit',
    name: 'Imperio Majapahit',
    name_en: 'Majapahit Empire',
    region: 'sudeste-asia',
    start_year: 1293,
    end_year: 1527,
    capital: 'Trowulan (Java oriental)',
    tags: ['imperio', 'hinduismo-budismo', 'java', 'naval'],
    wikidata: 'Q244062',
    sources: ['https://es.wikipedia.org/wiki/Majapahit'],
    body: 'Imperio talasocrático hindú-budista basado en Java, fundado por Raden Wijaya (1293 CE) tras repeler una invasión mongola. Bajo el primer ministro Gajah Mada (1336) extiende influencia sobre buena parte del archipiélago malayo. Considerado precursor de la identidad indonesia moderna (la noción Nusantara). Decadencia tras 1450 por sucesión y expansión del islam; absorbido finalmente por sultanatos islámicos (Demak).',
  },
  {
    id: 'reino-de-ayutthaya',
    name: 'Reino de Ayutthaya',
    name_en: 'Ayutthaya Kingdom',
    region: 'sudeste-asia',
    start_year: 1351,
    end_year: 1767,
    capital: 'Ayutthaya',
    tags: ['reino', 'thai', 'budismo-theravada', 'comercio'],
    wikidata: 'Q3556',
    sources: ['https://es.wikipedia.org/wiki/Reino_de_Ayutthaya'],
    body: 'Reino thai fundado por Ramathibodi I (1351 CE) en el delta del Chao Phraya. Centro comercial cosmopolita con presencia de mercaderes chinos, persas, malayos, holandeses y portugueses. Capital Ayutthaya descrita por viajeros europeos como una de las ciudades más impresionantes de Asia. Saqueada por los birmanos en 1767, lo que precipita la mudanza de la capital thai a Bangkok (Rattanakosin).',
  },

  // ─── Estepa / Asia Central (5) ────────────────────────────────────────────
  {
    id: 'escitas',
    name: 'Escitas',
    name_en: 'Scythians',
    region: 'estepa',
    start_year: -700,
    end_year: 200,
    capital: 'sin capital fija (nómada)',
    tags: ['nomada', 'caballeria', 'arte-animalista'],
    wikidata: 'Q193715',
    sources: ['https://es.wikipedia.org/wiki/Escitas'],
    body: 'Confederación de pueblos iranios nómadas de la estepa euroasiática, dominantes desde el Mar Negro hasta el Altái durante casi un milenio. Caballería montada con arco compuesto, arte zoomorfo distintivo en oro. Heródoto los describe como hábiles guerreros que vencieron a Darío I (513 BCE) mediante táctica de tierra quemada. Absorbidos por sármatas y otros pueblos esteparios hacia el siglo III CE.',
  },
  {
    id: 'imperio-xiongnu',
    name: 'Imperio Xiongnu',
    name_en: 'Xiongnu Empire',
    region: 'estepa',
    start_year: -209,
    end_year: 89,
    capital: 'sin capital fija (yurta del Chanyu)',
    tags: ['imperio', 'nomada', 'caballeria', 'rival-han'],
    wikidata: 'Q170424',
    sources: ['https://es.wikipedia.org/wiki/Xiongnu'],
    body: 'Confederación nómada esteparia que dominó el norte de China y Asia Central. Su unificación bajo Modu Chanyu (209 BCE) precipita la construcción de la Gran Muralla por los Han. Conflicto centenario con China — el sistema heqin (matrimonios diplomáticos y tributo) y luego campañas ofensivas de Wu Di. Fragmentación interna y derrota Han llevan a su desintegración hacia 89 CE. Posible conexión con los hunos europeos posteriores (debatida).',
  },
  {
    id: 'khaganato-turco',
    name: 'Khaganato Turco',
    name_en: 'Turkic Khaganate',
    region: 'estepa',
    start_year: 552,
    end_year: 744,
    capital: 'Ötüken (montañas Khangai)',
    tags: ['khaganato', 'turco', 'nomada', 'eje-norte-sur'],
    wikidata: 'Q229538',
    sources: ['https://es.wikipedia.org/wiki/Imperio_turco'],
    body: 'Primer estado en autodenominarse "turco". Fundado por Bumin Qaghan (552 CE), llega a controlar desde Manchuria hasta el Mar Negro. Dividido en Khaganato Oriental y Occidental tras 581 CE. Estelas de Orkhon (732 CE) son los primeros testimonios escritos en lengua turca. Decadencia por presiones chinas (Tang) y árabes; sucedido por uigures, kirguises y otros pueblos turcos.',
  },
  {
    id: 'imperio-mongol',
    name: 'Imperio Mongol',
    name_en: 'Mongol Empire',
    region: 'estepa',
    start_year: 1206,
    end_year: 1368,
    capital: 'Karakorum → Janbalik (Beijing)',
    tags: ['imperio', 'nomada', 'mayor-imperio-territorial', 'pax-mongolica'],
    wikidata: 'Q12132',
    sources: ['https://es.wikipedia.org/wiki/Imperio_mongol'],
    body: 'Imperio terrestre contiguo más grande de la historia, fundado por Genghis Khan (1206 CE). Conquistas masivas en una sola generación: Asia Central, China del Norte (Yuan), Persia (Ilkanato), Rusia (Horda de Oro), parte del Levante. La Pax Mongolica (~1250-1350) facilita comercio y comunicación euroasiática (viaje de Marco Polo, transmisión de pólvora a Europa, posiblemente la Peste Negra). Fragmentación en kanatos tras 1260, fin formal del Yuan en 1368.',
  },
  {
    id: 'imperio-timurida',
    name: 'Imperio Timúrida',
    name_en: 'Timurid Empire',
    region: 'estepa',
    start_year: 1370,
    end_year: 1507,
    capital: 'Samarcanda',
    tags: ['imperio', 'islam', 'persa-turco', 'arquitectura'],
    wikidata: 'Q207320',
    sources: ['https://es.wikipedia.org/wiki/Imperio_timúrida'],
    body: 'Imperio fundado por Tamerlán (Timur Lenk, 1370 CE), turcomongol musulmán que reivindica continuidad genghiskhánida. Brutal conquistador y a la vez mecenas: Samarcanda alcanza su apogeo arquitectónico. Sucesor Ulugh Beg construye un observatorio astronómico de referencia mundial. Fragmentación tras 1500; Babur, descendiente timúrida, funda el Imperio Mogol en India.',
  },

  // ─── Américas (6) ─────────────────────────────────────────────────────────
  {
    id: 'caral',
    name: 'Civilización Caral / Norte Chico',
    name_en: 'Caral-Supe / Norte Chico Civilization',
    region: 'americas',
    start_year: -3500,
    end_year: -1800,
    capital: 'Caral',
    tags: ['civilizacion', 'pre-ceramica', 'andes'],
    wikidata: 'Q47369',
    sources: ['https://es.wikipedia.org/wiki/Civilización_caral'],
    body: 'Civilización más antigua de las Américas, contemporánea de Sumeria, Egipto antiguo y el Valle del Indo. Sitios monumentales (Caral, Áspero, Bandurria) en la costa norte de Perú. Notable por ser pre-cerámica y por la ausencia aparente de fortificaciones — sociedad compleja sin evidencia clara de guerra organizada. Quipus (sistemas de cuerdas anudadas) como posible escritura/contabilidad — pre-incas en ~4000 años.',
  },
  {
    id: 'maya-clasico',
    name: 'Civilización Maya (Periodo Clásico)',
    name_en: 'Classic Maya Civilization',
    region: 'americas',
    start_year: 250,
    end_year: 900,
    capital: 'sin capital única (ciudades-estado: Tikal, Palenque, Copán, Calakmul)',
    tags: ['civilizacion', 'mesoamerica', 'escritura', 'astronomia'],
    wikidata: 'Q12277',
    sources: ['https://es.wikipedia.org/wiki/Cultura_maya'],
    body: 'Civilización mesoamericana de ciudades-estado en la península de Yucatán y tierras bajas mayas. Único sistema de escritura completo desarrollado en las Américas pre-colombinas (logosilábico maya). Logros: matemáticas con cero independiente, calendarios solar de 365 días y ceremonial de 260 días, predicción astronómica de eclipses, observatorios. El "colapso clásico" (~800-900) interrumpe las ciudades del sur; tradiciones continúan en el norte (Chichén Itzá) hasta la conquista española.',
  },
  {
    id: 'cahokia',
    name: 'Cahokia / Cultura Mississippiana',
    name_en: 'Cahokia / Mississippian Culture',
    region: 'americas',
    start_year: 800,
    end_year: 1600,
    capital: 'Cahokia (cerca de la actual St. Louis)',
    tags: ['civilizacion', 'norteamerica', 'monticulos', 'jerarquica'],
    wikidata: 'Q220688',
    sources: ['https://es.wikipedia.org/wiki/Cahokia'],
    body: 'Centro urbano más grande de la Norteamérica pre-colombina, situado cerca de la confluencia del Misisipi y el Misuri (actual Illinois). En su apogeo (~1100 CE) tenía 15,000-20,000 habitantes y un montículo central (Monks Mound) que es la estructura de tierra más grande de las Américas. Centro de la cultura mississippiana — agricultura del maíz, montículos ceremoniales, intercambio a larga distancia. Abandonada hacia 1400 por razones aún debatidas.',
  },
  {
    id: 'imperio-azteca',
    name: 'Imperio Azteca (Triple Alianza)',
    name_en: 'Aztec Empire',
    region: 'americas',
    start_year: 1428,
    end_year: 1521,
    capital: 'Tenochtitlan',
    tags: ['imperio', 'mesoamerica', 'mexica', 'tributario'],
    wikidata: 'Q83515',
    sources: ['https://es.wikipedia.org/wiki/Imperio_azteca'],
    body: 'Hegemonía mesoamericana liderada por los mexicas, formada con la Triple Alianza entre Tenochtitlan, Texcoco y Tlacopan (1428). Sistema tributario que dominaba el centro de México. Capital Tenochtitlan, construida sobre el lago Texcoco, llega a ~200,000 habitantes — más grande que cualquier ciudad europea contemporánea. Conquistada por Hernán Cortés (1519-1521) aprovechando alianzas con tlaxcaltecas y otros pueblos sometidos al tributo mexica.',
  },
  {
    id: 'imperio-inca',
    name: 'Imperio Inca (Tawantinsuyu)',
    name_en: 'Inca Empire (Tawantinsuyu)',
    region: 'americas',
    start_year: 1438,
    end_year: 1572,
    capital: 'Cuzco',
    tags: ['imperio', 'andes', 'quechua', 'sin-escritura', 'mit-a'],
    wikidata: 'Q11778',
    sources: ['https://es.wikipedia.org/wiki/Imperio_incaico'],
    body: 'Mayor imperio pre-colombino de las Américas, abarcando los Andes desde el sur de Colombia hasta el centro de Chile. Expansión rápida bajo Pachacuti (1438) y Túpac Yupanqui. Notable por la ausencia de escritura propia — administración mediante quipus, sistema de cuerdas anudadas. Red de caminos (Qhapaq Ñan) de >30,000 km. Conquistado por Francisco Pizarro tras la captura de Atahualpa (1532); resistencia en Vilcabamba hasta 1572.',
  },
  {
    id: 'moche',
    name: 'Civilización Moche',
    name_en: 'Moche Culture',
    region: 'americas',
    start_year: 100,
    end_year: 800,
    capital: 'Huacas de Moche / Pampa Grande',
    tags: ['civilizacion', 'andes', 'metalurgia', 'huacas'],
    wikidata: 'Q160063',
    sources: ['https://es.wikipedia.org/wiki/Cultura_mochica'],
    body: 'Civilización de la costa norte del Perú, predecesora cultural de los incas. Famosa por su cerámica retrato realista, metalurgia avanzada (Señor de Sipán, ~250 CE — descubierto en 1987 con uno de los ajuares funerarios más ricos de las Américas), arquitectura monumental de adobe (Huaca del Sol y de la Luna). Sistemas de irrigación sofisticados en zona desértica. Decadencia hacia el siglo VIII, posiblemente por eventos ENSO extremos.',
  },
];
