// 10 tradiciones religiosas canónicas para v1 (PLAN §F4/paso-1).
// Decisión editorial: tratamos "religiones indígenas" como cluster único en
// lugar de individualizar cientos de tradiciones pre-cristianas/pre-islámicas/etc.
// que romperían la escala de la banda religiosa del histomap.

export const RELIGIONS_SEED = [
  {
    id: 'judaismo',
    name: 'Judaísmo',
    name_en: 'Judaism',
    start_year: -1800,
    end_year: null,
    region_birth: 'medio-oriente',
    branch_of: null,
    branches: ['cristianismo'],
    color: '#1A237E',
    tags: ['abrahamica', 'monoteismo', 'rabinico'],
    wikidata: 'Q9268',
    sources: ['https://es.wikipedia.org/wiki/Judaísmo'],
    body: 'Tradición religiosa de los hebreos / judíos, atribuida tradicionalmente al pacto entre Abraham y Yahvé (~1800 BCE), institucionalizada con el éxodo y la Torá. Núcleo: monoteísmo ético, alianza, ley (halajá). Después de la destrucción del Segundo Templo (70 CE) el judaísmo rabínico desplaza al templário; diáspora milenaria con tradiciones sefardí, ashkenazí, mizrahí.',
  },
  {
    id: 'cristianismo',
    name: 'Cristianismo',
    name_en: 'Christianity',
    start_year: 30,
    end_year: null,
    region_birth: 'medio-oriente',
    branch_of: 'judaismo',
    branches: [],
    color: '#8B4513',
    tags: ['abrahamica', 'monoteismo', 'trinitario'],
    wikidata: 'Q5043',
    sources: ['https://es.wikipedia.org/wiki/Cristianismo'],
    body: 'Fundada en torno a la figura de Jesús de Nazaret (~4 BCE - 30 CE) y su muerte/resurrección según la tradición. Pasa de movimiento judío sectario a religión oficial del Imperio Romano (Edicto de Tesalónica, 380 CE). Cisma Oriente/Occidente (1054), Reforma Protestante (1517). Hoy ~2.4B adherentes globales, dividida en tres grandes familias (católica, ortodoxa, protestante) y miles de denominaciones.',
  },
  {
    id: 'islam',
    name: 'Islam',
    name_en: 'Islam',
    start_year: 622,
    end_year: null,
    region_birth: 'medio-oriente',
    branch_of: null,
    branches: [],
    color: '#2E7D32',
    tags: ['abrahamica', 'monoteismo', 'sunni-chi-a'],
    wikidata: 'Q432',
    sources: ['https://es.wikipedia.org/wiki/Islam'],
    body: 'Tradición monoteísta abrahámica revelada según la tradición a Mahoma (570-632) entre Meca y Medina. La Hégira (622 CE, calendario islámico año 1) marca su inicio formal. Cisma temprano sunita/chiita por la sucesión califal (657). Cinco pilares (shahada, salat, zakat, sawm, hajj). Hoy ~1.9B adherentes; los mayoritarios son sunitas (~85%).',
  },
  {
    id: 'hinduismo',
    name: 'Hinduismo',
    name_en: 'Hinduism',
    start_year: -1500,
    end_year: null,
    region_birth: 'sur-asia',
    branch_of: null,
    branches: [],
    color: '#FF8F00',
    tags: ['indica', 'politeismo-henoteismo', 'samsara'],
    wikidata: 'Q9089',
    sources: ['https://es.wikipedia.org/wiki/Hinduismo'],
    body: 'Conjunto sincrético de tradiciones del subcontinente indio sin fundador ni canon único, codificadas en Vedas (~1500-500 BCE), Upanishads, Mahabharata, Bhagavad Gita. Núcleo conceptual: dharma, karma, samsara, moksha. Diversidad teológica (no-dualismo Advaita, dualismo Dvaita, devocional bhakti) con tres deidades principales (Brahma-Vishnu-Shiva). Hoy ~1.2B, mayormente en India y Nepal.',
  },
  {
    id: 'budismo',
    name: 'Budismo',
    name_en: 'Buddhism',
    start_year: -500,
    end_year: null,
    region_birth: 'sur-asia',
    branch_of: null,
    branches: [],
    color: '#FBC02D',
    tags: ['indica', 'no-teista', 'cuatro-nobles-verdades'],
    wikidata: 'Q748',
    sources: ['https://es.wikipedia.org/wiki/Budismo'],
    body: 'Fundado por Siddhartha Gautama (~563-483 BCE) en el norte de India. Cuatro Nobles Verdades + Óctuple Sendero como camino de cese del sufrimiento (dukkha). Expande masivamente bajo el patrocinio del rey Ashoka (~250 BCE). Tres tradiciones principales: Theravada (Sri Lanka, Sudeste Asiático), Mahayana (Este de Asia), Vajrayana (Tíbet, Mongolia). Declina en India medieval pero permanece dominante en buena parte de Asia.',
  },
  {
    id: 'jainismo',
    name: 'Jainismo',
    name_en: 'Jainism',
    start_year: -600,
    end_year: null,
    region_birth: 'sur-asia',
    branch_of: null,
    branches: [],
    color: '#FFEB3B',
    tags: ['indica', 'no-teista', 'ahimsa'],
    wikidata: 'Q9899',
    sources: ['https://es.wikipedia.org/wiki/Jainismo'],
    body: 'Tradición contemporánea del budismo temprano, codificada por Mahavira (~599-527 BCE) como el último Tirthankara de una serie ancestral. Énfasis radical en ahimsa (no-violencia hacia todos los seres), ascetismo, y la doctrina de los muchos puntos de vista (anekantavada). Dos comunidades principales: Digambara y Svetambara. Hoy ~6M adherentes, mayormente en India.',
  },
  {
    id: 'daoismo',
    name: 'Daoísmo',
    name_en: 'Daoism / Taoism',
    start_year: -400,
    end_year: null,
    region_birth: 'este-asia',
    branch_of: null,
    branches: [],
    color: '#37474F',
    tags: ['china', 'naturalista', 'wu-wei'],
    wikidata: 'Q9598',
    sources: ['https://es.wikipedia.org/wiki/Taoísmo'],
    body: 'Tradición china codificada en el Dao De Jing atribuido a Laozi (~6º BCE, datación debatida) y desarrollada por Zhuangzi. Concepto central del Dao (el "camino" cosmológico) y wu wei (acción sin esfuerzo en armonía con la naturaleza). Convive sincréticamente con confucianismo y budismo en China (las "tres enseñanzas"). Tradiciones derivadas: alquimia interna, medicina tradicional, prácticas energéticas (qigong).',
  },
  {
    id: 'confucianismo',
    name: 'Confucianismo',
    name_en: 'Confucianism',
    start_year: -500,
    end_year: null,
    region_birth: 'este-asia',
    branch_of: null,
    branches: [],
    color: '#5D4037',
    tags: ['china', 'etica-civica', 'literati'],
    wikidata: 'Q5683',
    sources: ['https://es.wikipedia.org/wiki/Confucianismo'],
    body: 'Sistema ético-político codificado por Confucio (Kong Fuzi, ~551-479 BCE) y desarrollado por Mencio y Xunzi. Énfasis en ren (humanidad), li (rito/decoro), xiao (piedad filial), junzi (caballero virtuoso). Ideología oficial de la China imperial desde Han (~136 BCE) hasta el fin de Qing (1912), administrada vía los exámenes imperiales. Renacimiento neoconfuciano bajo Song (Zhu Xi, ~1175).',
  },
  {
    id: 'zoroastrismo',
    name: 'Zoroastrismo',
    name_en: 'Zoroastrianism',
    start_year: -1000,
    end_year: null,
    region_birth: 'medio-oriente',
    branch_of: null,
    branches: [],
    color: '#D32F2F',
    tags: ['persa', 'dualismo', 'parsi'],
    wikidata: 'Q9601',
    sources: ['https://es.wikipedia.org/wiki/Zoroastrismo'],
    body: 'Tradición fundada por el profeta Zaratustra (Zoroastro, datación entre 1500 y 600 BCE) en Persia. Dualismo cósmico Ahura Mazda (bien) vs. Angra Mainyu (mal), con responsabilidad ética del individuo. Religión oficial de los imperios Aqueménida, Parto y Sasánida. Influencia profunda en cosmologías abrahámicas posteriores (concepción del diablo, fin de los tiempos). Hoy ~100-200k adherentes (parsis en India, zoroastrianos en Irán).',
  },
  {
    id: 'religiones-indigenas',
    name: 'Religiones indígenas (cluster)',
    name_en: 'Indigenous religions (cluster)',
    start_year: -10000,
    end_year: null,
    region_birth: 'americas',
    branch_of: null,
    branches: [],
    color: '#6D4C41',
    tags: ['cluster', 'animismo', 'chamanismo', 'pre-monoteismo'],
    wikidata: null,
    sources: ['https://es.wikipedia.org/wiki/Religiones_étnicas'],
    body: 'Cluster narrativo que agrupa las tradiciones religiosas pre-monoteístas y de pueblos originarios a lo largo de toda la historia humana: animismo, totemismo, culto a antepasados, chamanismo, religiones de la naturaleza. Incluye tradiciones americanas (mayas, aztecas, incas, pueblos indígenas norteamericanos), africanas (yoruba, akan, voduismo pre-colonial), del Sudeste Asiático, oceánicas, esteparias. Cluster por necesidad de escala en el histomap; en realidad son cientos de tradiciones distintas.',
  },
];
